"""Defines OpenTofu module check targets for GCP cell topology composition and testing."""

load("@rules_tf//tf:def.bzl", "tf_module")
load("//src/bazel/rules/build_graph_coverage:defs.bzl", "package_sources")

tf_module(
    name = "gcp",
    providers = [
        "google",
    ],
    deps = [
        "//src/infra/terraform/components/cluster/gcp",
        "//src/infra/terraform/components/dns/gcp",
        "//src/infra/terraform/components/identity/gcp",
        "//src/infra/terraform/components/network_mesh/gcp",
        "//src/infra/terraform/components/secret_manager/gcp",
        "//src/infra/terraform/components/storage/gcp",
        "//src/infra/terraform/components/vpc/gcp",
        "//src/infra/terraform/topologies/cell/_interface",
    ],
)

package_sources()
