# Helm values configuring Kuberhealthy operator, resource limits, and minimal checks.

fullnameOverride: kuberhealthy

imageURL: docker.io/kuberhealthy/kuberhealthy:v3.0.17@sha256:4e55bbc72ab252115dec1f596d2441de3eabe565fb540c075e6a8b1a68674fa2

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

deployment:
  replicas: 1
  imagePullPolicy: IfNotPresent
  podAnnotations:
    automount-service-account-token: "true"
  env:
    KH_CHECK_REPORT_URL: "http://kuberhealthy.kuberhealthy.svc.cluster.local:8080"

serviceAccount:
  annotations:
    automount-service-account-token: "true"

securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 999
  fsGroup: 999
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

podDisruptionBudget:
  enabled: false

service:
  externalPort: 8080
  type: ClusterIP
