# Configures Atlantis pull-request automation workflows and project root directories for Terraform plans.

version: 3
automerge: true
autodiscover:
  mode: disabled
projects:
  # keep-sorted start block=yes
  - name: dns
    dir: src/infra/terraform/deployments/dns
    workflow: fleet
    apply_requirements: [approved, mergeable, undiverged]
    autoplan:
      enabled: true
      when_modified:
        # keep-sorted start
        - "*.tf*"
        - ../../../../.github/atlantis.yaml
        - .terraform.lock.hcl
        - deployment.yaml
        # keep-sorted end
  - name: research
    dir: src/infra/terraform/deployments/research
    workflow: fleet
    apply_requirements: [approved, mergeable, undiverged]
    autoplan:
      enabled: true
      when_modified:
        # keep-sorted start
        - "*.tf*"
        - ../../../../.github/atlantis.yaml
        - ../../../argocd/components/tailscale_access/cloud-policy.hujson
        - ../../../definitions/**
        - ../../components/**
        - ../../topologies/**
        - .terraform.lock.hcl
        - deployment.yaml
        # keep-sorted end
# keep-sorted end
