"""Defines OpenTofu module check targets for AWS cell topology composition and testing."""

load("@rules_tf//tf:def.bzl", "tf_module")
load("//src/bazel/rules/build_graph_coverage:defs.bzl", "package_sources")

tf_module(
    name = "aws",
    providers = [
        "aws",
    ],
    deps = [
        "//src/infra/terraform/components/cluster/aws",
        "//src/infra/terraform/components/dns/aws",
        "//src/infra/terraform/components/identity/aws",
        "//src/infra/terraform/components/network_mesh/aws",
        "//src/infra/terraform/components/secret_manager/aws",
        "//src/infra/terraform/components/storage/aws",
        "//src/infra/terraform/components/vpc/aws",
        "//src/infra/terraform/topologies/cell/_interface",
    ],
)

package_sources()
