# Defines the ServiceAccount for the local storage inventory producer CronJob.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-inventory-producer
  namespace: s3-system
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: local-storage-inventory-producer
automountServiceAccountToken: false
