# Generated by src/bazel/module_deps/update_tofu_providers_lock.sh; do not edit.
# Regenerate with: mise exec -- src/bazel/module_deps/update_tofu_providers_lock.sh
# One `tofu providers lock` block per tf.download mirror coordinate in MODULE.bazel.
# The tf extension fails when a registry sha256 is not among its zh: hashes.

provider "registry.opentofu.org/cloudflare/cloudflare" {
  version     = "5.24.0"
  constraints = "5.24.0"
  hashes = [
    "h1:EdatAvZg845pGYfEdzYNkxmQfV8or5y6HDbh6CIJfI8=",
    "h1:F3V4hF42Y/Usl9OhzNFQHwUL8oNXTzbY5x6dQaDaASc=",
    "h1:HR6WGGeB70a/yygHbNFsg+3Ko7s9AgtlkFf8PdbZfT8=",
    "h1:NxZYEFjCgaI7lGi3L8mn0KZcWPfbqUdmt5Bo4yqWMFE=",
    "h1:PIAng5QYiHeydJm1S6sG6d1YYIjaFuIwnifvq/qEV1Q=",
    "h1:R1Pt6vcenzSH8FDbxW1MQ3tk+/nXAfvscASTFaOmERM=",
    "h1:ZGuBr8oAhWpWIni1jaNofXcsNUoaHuejjHcbcH72z1Q=",
    "h1:yM0PvkOY7H66+yk+vlDJOnhDQXOFT6cHlmZ/C6UjT/c=",
    "zh:2390fc5df95addfd47d3f638964a1f9f6192a8c84ad3b1eab554ef88e0ac4091",
    "zh:2b09c0afbebeb3139a3094e3debda1ba5ff3d73b6eca536549bdc903284b6798",
    "zh:3241ce471f20745b1dc93baea73a716e1db4637ff41acc134114b7a8c9684714",
    "zh:3513243e5582836054076a21abeadd8142a8421df6ec1ead53d96dc37a9e6326",
    "zh:99b33ccb8a1c10a08e8903a2848eb2664c889dc79801a1e61e0373dd41c6c0f9",
    "zh:99c7b510b100a605b0c80e0c3665d99c2381b0834f52ad6ca767e161c2ffa416",
    "zh:c523d747a2d8457bc2d2cc00967c419ef38a5ebebd12d5091cf18322b7201f04",
    "zh:f520e37f4d875b6fee95cffb74cf5fe9efc3cd54fe6bb4b815da5cee87e517e8",
    "zh:f809ab383cca0a5f83072981c64208cbd7fa67e986a86ee02dd2c82333221e32",
  ]
}

provider "registry.opentofu.org/hashicorp/archive" {
  version     = "2.8.0"
  constraints = "2.8.0"
  hashes = [
    "h1:4a8R2WlgZ3LUBXqR2/LqeAu5Q9Unjsh1jbc1XLbQW2I=",
    "h1:5Rcf7ostJMCWpo0EYrldMu+Fq1T23ldisLXGfv4SZmE=",
    "h1:9/wf/bw1G76APmrMENARfP++S3kJGOdOu1gEUmZHaag=",
    "h1:BEA9Ass5e0tn5f8st/h+IxEFJaeocRtBTW6VcGivBJg=",
    "h1:H84fIYOLWMtVduFn5q3HlkSR56SIuM/8rJCZXFc8ckU=",
    "h1:LbnG2K/sbXn52fdEjztAKG4GOli+G/KgadD4XHyaTlE=",
    "h1:NTDoNvS6EccEDIhZQUDoYVOpJz1HDZ+ZW5abIG27YjA=",
    "h1:PjxW7g7rSqZQtcHB0YnvZpdCocPMw9w35pAWEcfLY9Q=",
    "h1:YjAw6RUZ6UxWgLaWf58j5LjzvPuuNuF4/pxD+yqkOhs=",
    "h1:dk3u86A+/wA+2tPJChUgPFJV+r8ow+55Qyh7wTth9AE=",
    "h1:gl6Z86IQ2Xxix+19cfsPJ3IKwXCs+vqA4MqLfTG/vtk=",
    "h1:hct6U5rz1ns287sMtI1b3xGI1h84CXRb0ztXXvN+VKM=",
    "h1:lCfMh04aemFQ4cAUalcxAprp4mVVsgd15Qs84FIAbX0=",
    "h1:npbdnq+7TdLuorM4sjQ5MCpgLZ0zX2heIqjdo+FhtqI=",
    "h1:xS7wTQ2aqTXwvLCZcXShHcVIlpziaZh+5/1HMUHrizQ=",
    "zh:0b8b21e163dd07ee92aeb8085b6c47c0226d8dff7f0a585c042e2050743102f1",
    "zh:40afcd5d2f4e7d4a10ba053698ea9981170121731bfe90de78f907e159c68f72",
    "zh:59be391e1362e8249b3bbebef28ee406464926330a32a10e7e984dd957070e15",
    "zh:685f07c325946bc533d68143dee789a32d0f5c1b3b88c6a8d4c96d8a74b3632f",
    "zh:733cdc39e964d5294ecc1a7d595d0d22df97e2040c0a85ed17fd352487cbb51b",
    "zh:7e100b9dfbfa0eb295921eeba0670652b04de78f598c1f77f0f0b47868373e5a",
    "zh:8c1e6bf711ef5c96ff81923e51b075c41710b193fa3625e3c18d4e8ef629fa9d",
    "zh:8dc06ee505a94f85479c946fe9ac496a93ee6372b8c7747a19d13efb19d337ca",
    "zh:933c20fd5cba9016b9659add7bc2af80c8ef28e80c1bf3bdb4742de4a86f2bb4",
    "zh:939709283eae390ee3e790e94ac8a5c5da555bb59addd0281a33e9a88b1ec697",
    "zh:b713c8b05018a9f20a03d33207c3673857c21788639d01ce4c8752b92de83527",
    "zh:b7ffa7c816458adff82d4a3cf3c0eadc76122a54be2c78667ad3fcc33ca5544c",
    "zh:c1d9328d8928a43c182e09a5f8d47669e007911639bec603360928f70c74e61a",
    "zh:c6f4958fea5f69b23d408b50e7d40ec724cd281f6327a77d5335919484561ea3",
    "zh:c9356b8c980bbd1b702f6ccdc11e2f938b0325e99869b022b58d5299153ea65e",
  ]
}

provider "registry.opentofu.org/hashicorp/aws" {
  version     = "6.66.0"
  constraints = "6.66.0"
  hashes = [
    "h1:A2L/03k6fbOyb8Pg6224b9vajh285FZDvlWdgaO2Fkw=",
    "h1:HbcFNt1OvD4MBknLg/m0rg7grEaKlaSUbnecF3vxvx0=",
    "h1:KEKMmD7afHqcJdw54IFJmXE+59xgh9LJlpXhemEN6H0=",
    "h1:LBazejB2S9h3e2kmXI8QDSVA11U2JEW4XSDs1c/S1P0=",
    "h1:PWE6gqi8Mg8crSuvxb5KmrR0rFoddB4WbpIdSHRC59U=",
    "h1:QLqaOtzPyuv1vdT4NuAgVOGCld9Pk3eWAW9u8z102lI=",
    "h1:UHgIgYN6WcVabz8xOAzKX4Iet+XNTyOJvvVMCWLkoCw=",
    "h1:YNwRhbk68IhAHqL1x2D9zj0BhY8qqyPLO+zTQOdfMpM=",
    "h1:av0q2IS8IaCEvxSg8O9aapxHTyKOeeaXT++IeWZPz2Y=",
    "h1:bUp871GCBdQOMB4TC6ND/+k64QjHmYkqqfQPh682kew=",
    "h1:dSXxrFpGyQ1obQeGZQw5iA54LBx58z9XZhDZTtV6m+c=",
    "h1:dnGqQEhsy2djusN1G6JJgfjkGoQREYEmNpvJD/fZycU=",
    "h1:hkkPlR574ztoxUs76kSsS8tnxfjVFqpWZOFlffPqVRQ=",
    "h1:jvqzmQntdO80OzKw9ikpCUsQZVK3/mznM1Eie9tIspE=",
    "h1:o6+yfy74tYUxiD4jMxB/TzGNlVYvLExG+BLrIH9enS8=",
    "zh:005994add988d9acdd291a10641d27ef828246cb4c4c66e82317bd0012d4b79e",
    "zh:387e8ba5af9d628e36ca554453d5f664c1649c475fac92e7b3a23bc01e0a7d31",
    "zh:45acbc6df5900c070a7db81b8286b54b7366a7d973f9c186a06be4de0b59c229",
    "zh:533dc482c05948a005355ad5263ab832ae01eb137a8fceec2b3bf63cb00fad72",
    "zh:5d3fe32f05510182a43fca628312ba916cabef61dfc4cabfe7fb84326e509894",
    "zh:7d2dc52b6e0a245565ae92fc07926fd9284ae4e1f35b148053b1cc80615a3e66",
    "zh:8bbb54f340d98db06d93ef34cab6560fb89a18e8c07af2e7085789701ec7a7ce",
    "zh:97904961a5c1813c200ab51a20831dd76c3cc6bf262cb9e34ea9b1afdde05216",
    "zh:a26c7bb1ad5ecb691bb2558dde9eb13827fdf326b855ab8e522f74c91a0aa475",
    "zh:ab9c77d4427bf7a118b8e666c9bc90cc128662301b27dc2fcbb9653019a07a82",
    "zh:d467d3ca59c526dc5ee7e0d6bfa87151dbcfade1fa81e1b48af7a582b4aabe7a",
    "zh:dcd3e32777e9db4d679f732f0f73dbb9a51ebe94beef264276b7ea6e8ee2d83b",
    "zh:e2ded7927ea0a6941d91e675bc25b89f93eb466ae3e782f47a83b7401f8fc447",
    "zh:ecce136f374f456638192e12bfd11ba7561434789b38a9c76d303d5f622f38ea",
    "zh:fc60d067c52a1975841eb5dc20faa31763cd1cbbe2f017a1ff9598e7038a7590",
  ]
}

provider "registry.opentofu.org/hashicorp/google-beta" {
  version     = "7.45.0"
  constraints = "7.45.0"
  hashes = [
    "h1:0+Q/xe+Rgn+X6i4C+pmDOqlG4BheYLAzvg7s2KiHD7s=",
    "h1:2diUo+hOvjnxaXAI3COykfISwOWd0XUt4FBev61byNQ=",
    "h1:6WcVToUwdrgYi7T9epn7KUgpONxypdSlq1BATDNxqDw=",
    "h1:BX0Wep2JLmnozEyjXDg48UlQLd7FYjQv0p+PSOeVES0=",
    "h1:Dg/Z4CDXVla0iz3BAFSLxx12d1akT1eCmCbkyxzNNEs=",
    "h1:EjE86Yc7EGw1CiJYlIJr+2AdDlkFBvtDybLrG1f4wqc=",
    "h1:HOJrHl2VNU9kMfwn9Pbge4Sdu5TMrv8jSpvOeG+Frpk=",
    "h1:OolSd0g9iMcCpcufdi23DI3hVLjw8WmljRzeBDaVqIA=",
    "h1:XhlQCDqVSz82InFGsyZPxn2HrXK7p++BPDLsAVKqIOQ=",
    "h1:db1kzZHhS+QpgETybHMUnsFRKpY3PFK9CQze2MnYgjM=",
    "h1:dyaoPU6mD2woyTDIeqp1yCAUPcM0ORDye6JaGnhnz/s=",
    "h1:mxJoAcPCJomm43WcxtrH3XnrSqbQbPU7BaVx7F1wEsM=",
    "h1:tzP+P9PeZH2y/+8f3bDU9bjr7lbV5bU0diXGIcj2+IM=",
    "h1:woE3LHWktlv1ugztMXJ2Z3joTaByjH35SErKIEvR9Zk=",
    "h1:zR1DYUdD2JUiEh5E/xYSzfmBH88AxBuYs6mOHoKsyWU=",
    "zh:09535cb193fadf41ca5957e28a93ce622407ee8cd6f7ae33d4bbf8695530ea10",
    "zh:0a7cad8112f9c7fe006bbbcffca6ab26cfd4b9d04d74215e904f8ab67ff50f1d",
    "zh:0d17b8d2fa04fb029d74fa613de55af9230854ecdd6b62cfba0051a876c8b024",
    "zh:1c3815ef5ca1831c9efe99c8e961abb15e19fef8fa596ead4ba504138e45b4eb",
    "zh:3a5cb54bf37083e7a08f131492f99f4bcd902055b3504d4ec0a207461f8cad6d",
    "zh:5c57a34e0315bb72e41aa2f96c3f8a9690e9be83aee8fdc3c79ecdf066e7498c",
    "zh:6378ee766c094b1e6a8433bf54a6e7559f57954c8ed32d3103f1e910ea97802f",
    "zh:765b720ae1eb635837dd591f4a4c6b2915618157aa849a7243705780bd324d6a",
    "zh:7f62971e8e2009518e6f7045a863d366697f9355b2917cfe7471e746fd74909f",
    "zh:a3212106b964d5cd10f9b2fdd0ce7abe60849fb1a16b57f9aa8a16102e76577f",
    "zh:bc8daa2508aac6d1b98c3774f1d20d96ae6aca507f938a68ce86affbf115a1af",
    "zh:bce4be3e2e84dd7203d6de92cc1e25c3a02b25f0951c192346ee10d6c8f06d39",
    "zh:c8ab4835ff3c237d9f8ae42249ad4a66c7e07500f3deddd7f0feec547118079e",
    "zh:d09db961306237a7861e466b53d23428ade1fac2a68b896ce0044a1c1c297e85",
    "zh:fada263689d0bdb535e2d0adf7eefafd257f2713b080a65fdfcab1a0a8096d4e",
  ]
}

provider "registry.opentofu.org/hashicorp/google" {
  version     = "8.4.0"
  constraints = "8.4.0"
  hashes = [
    "h1:/AaxJZVfEyh1BH7Z8GZupkxqpYjhIPiG7K/KaQS2Xgk=",
    "h1:1sByusL9mJSMZ8iQLXXdu+Nv1bh484rbic7K2y3XEbY=",
    "h1:5ko3SQxnDZ9onHH+oorWI+4e47FjknATCYVQXQz3JZI=",
    "h1:Ey15y6yC+J4sW1zS5JDGu3/bkrQwC0Sk/mzj5Kg52g0=",
    "h1:Hq83Fh4EQ9JrKO0F1D6RYRU2laNqO4XS9wPN43pS5+g=",
    "h1:IzV46n6zrjTrn6izJV9Yy2QqvhY4h9rdUqnk5IDbzSM=",
    "h1:L1YzvL6JYLPHxu3W10Fb4KN+ntoYnxEOxhgmiCj8CB8=",
    "h1:N6qi7xM3BzU0I1VTgB2HAOHAQ0jL85+wTlNeodGzq0U=",
    "h1:Sfk8FSyDceM8QcNFrN6iw1o4K27BrXkL3PuJxhcbiF8=",
    "h1:SxRLz574bOnGCDsmZkGC+P6LAg4uCPYyoRc2+Pq3WFI=",
    "h1:c5baopyrq3QnMEghXI2V2P+SIosYetlvAxXasG7UoRU=",
    "h1:d11Hc8/tgBXRTm/MMauvjuWZbYP1Pi2zMSpZeq9WRkU=",
    "h1:mNj6wPm2wJp7x6VaO+gMAm3u991h3wlkCS5+Gc8Ays0=",
    "h1:osBJ835p7+Yw8jPL306r7ZG5JccjoeFX28leUCPNjsY=",
    "h1:sssUq9QTSncbKmlyxZv3Zi0Q9b5mhMxS1haZEdJ/jAM=",
    "zh:15f76ac079b29fd182fac4630fe5d1e6079a88520c9adb57e8cabcfdf70724cd",
    "zh:22374f65c1bd1139d531030630ae5d87ca9c1e53d4678b957ca1ef550d711807",
    "zh:81eb3a5311a1812c03cb0e43fe335180cf36936b062daf08d94e465f3df517ee",
    "zh:8f6276810b5e27b9065d83d52fe13433c1ab4f05e67402cab82701da3bb04ddf",
    "zh:91f820b44e0b3f57fdd9dbeca38d54d24f7bc7199beffa602737ff3ddddd5e6c",
    "zh:9f4510269c4ae58bfb309cc658954990da9696bde70018702817c3da505d32ec",
    "zh:a23dc52a5eb41ee1d7234c0a2190af30c5c7dd232db80e1e08b3a3c378480ce4",
    "zh:ae044b6346b13364b5161927037c4ea216efd101adb3b93bf08364337c8aa0f9",
    "zh:b86ee0877be8d83ee2ca8991e694e3d39bfb5e89eac51dde5e6618c347e09692",
    "zh:bc22be3026fd57b37bdf0ec59038781661d831ad858382757e72a177f4cbd05b",
    "zh:cb2e8b6b0b0cabd37598f162624705ca76c94faac5dc581b8580bf06d45fd58b",
    "zh:eb0704bcd6ee7d568abe48c5c75038d617f16f15629f3e3a6f0de848210db7e4",
    "zh:ee0d79a4a0457d5cee9bedb570f5430d51e49fc4085f23c960607457100dfb8e",
    "zh:f54cb29b03becdbddc824c9812f1097f3fcc49804f14e201c71ada6dfdfdbd58",
    "zh:f79aef468d1645188de7ad60f68ecb848cf601d01e4c339051206f3421fde494",
  ]
}

provider "registry.opentofu.org/hashicorp/helm" {
  version     = "3.3.0"
  constraints = "3.3.0"
  hashes = [
    "h1:0zhsz9jzK+UxFNFYNJN904Hq1QYs9VMG4xPSumkKw/4=",
    "h1:3iVzjHzAq+YMymNbTq90zF20PeZu+ds1URRxhnoVRpg=",
    "h1:AYVZH0uO00tVS2VIMWfwTGkX+d1aloByZBbhdcDAxIo=",
    "h1:JJ9E97HlAUK2JZ/pdi0UZxZgBlNDq5dOjzrbLW3XK24=",
    "h1:JOepgsqVn+Fw+fY22j3hnA2Lj+W3S6RxPxPqokWJVAk=",
    "h1:MoUoWd56qOteNNVkYzKK5u5j7Xv/RAknMvZtm6PcTXo=",
    "h1:VZKsnRruH8EJRbgNk2jyTSPCYivOHOC03Q0JcXolLg8=",
    "h1:flPd03Uovsfo0ldt4rR17W1c8ibj2r7HQj+wGITWDGY=",
    "h1:hTuXyyFZQu7lIWRi9gjInX2OOcDDTuizLXWaX8fcE38=",
    "h1:jDTdMgfyGpYXyB14FI+Rqtf0A3HEDzYflXR2AGSOv3Q=",
    "h1:oR85nmKV3TSkBglrk77YaRcM5blLF6oeAqQZ9togpTE=",
    "h1:pH8KpcaZHzKxA2NQP7br0ap141z+G/mPwi59g4ozxHM=",
    "h1:uqQPsBGF0vlVz3WoResFm6AbJETVR0Vk+RMz+xzScuk=",
    "h1:xuZBFcoqxFfL6l20lS6fKVc66QPWQ9KFPycnvPIVG5c=",
    "h1:y5ZruUQcffAeqCU6mV1vZJYl96ijHc4GsQno/fOQ+Ng=",
    "zh:0a406aeadea91aa0feabd73ba27fe125f61993dfe760040f8bf35e3500b23e58",
    "zh:0e0c15a255c16857afa88f1a799496eef11db0815b4fdceb0902483a96c4f14a",
    "zh:29e894f6d09600a26b48510dac208f7742459f041ee6f640240f6e707b50591c",
    "zh:2c8cb4f322eb11396b053fde8f6e69cad689b46a15bddba458526342dae566db",
    "zh:330a3fe4c46175ffd5c9235d0337928fc2afd983020a0e1078a7ad74703f1852",
    "zh:44b37c8b20ae57eaca35e705625f97f9c1195915b2ef94b6d2890487cb27fb46",
    "zh:465aa9cfc5bc2e2e00cabb28f842b387eab58fdc44133bec7b9ee33f13c0adf0",
    "zh:5ac37a38cde4fb446f12c6ba8d8d775e0969f52cb19b6050de3c13f68a7c2374",
    "zh:759ededfe4245148acbc013da37fd592983ea1f1cb563d1b7c7a333eb2948654",
    "zh:84ac494bd529498b088bb6021fe4bce5ff365ad3468e6bcb5fc9fc8eed287437",
    "zh:88202f2941b795f4ac9e02ea1e6301f462778307eb3b39e8950a6a05fa2574af",
    "zh:8ddd111d58bc19bb9787093b64070238ce1d24cfaa63530456154936564135e8",
    "zh:95c9c38088148054bf3e9c7771e4a40f03e1c384084462489170a34fdfab398f",
    "zh:a2ab783211d5ebbadec3341618b565809db872eb61e0aad5093e38e2c2cb047f",
    "zh:a8439b77862dfc9bfe0c43a0710ac3cbcd113eb50e5cad3f8a78f2cd1ac11baa",
  ]
}

provider "registry.opentofu.org/hashicorp/kubernetes" {
  version     = "3.2.1"
  constraints = "3.2.1"
  hashes = [
    "h1:+VM77HEd3CgzxwQ0PtfOc5tQrRQ2FZ9YJj1ShiMTsoI=",
    "h1:32YYVAK/LUIheXfaxxnwL4qzf6QgWaMVkByneQH8EpA=",
    "h1:8WnHwjdwYmtpTJg5reAs9VGtKq67E3dQdIrcjDW1Xao=",
    "h1:8pNFJAX4IXSaPr+f02FsD6bUlZrMT5rkPPnA5sm2szI=",
    "h1:Ad9kERqM2KFLkW/beJ6VsV3QxD05o98ZjC/epjpDcnI=",
    "h1:EtS/ztrc03Vy+u9Q6eflu+HYVMMhQIufMaHS+vlbprY=",
    "h1:GROcvqLewzybvZa6LjWjU7EWE7aOttp9ovBkT1b8lhc=",
    "h1:OR1GGSnvGgFNKA8ilnttn1cy5wT8N0qzGpbqWOZ+yG8=",
    "h1:PJBBJz/9kOjaGjGXCQpVslstEbeTxQBx8zu/ZAvRHak=",
    "h1:QzzyadpGU0iHlOKsXX/ge6/apcwRXmzVlJxSzVclM/I=",
    "h1:Un9WHqrP13fUt64c7VcO60VfvJty0tnrX88b8wy/4SU=",
    "h1:VDyHxveT5+lt75fY3oOpa1D/08i1+AC6Af5XoQXEK7E=",
    "h1:glcBsCYHGLC1os31lZ22X0se9EyTjQO/1kVMeHj5uJ8=",
    "h1:qGon41gIBlkXIbSpsovc5UJr4okWcjaw7KkgPFxhNlU=",
    "h1:tsq7mekr30obQVOK83ZNAiRb7rzRSZnWxQLdjD1Rvo0=",
    "zh:018e382285ab0ca5a68e4e4116e1cfc3a20c57194f4e678bd87654f5aecf5b14",
    "zh:0e8d233199b6896a6b9379b2f41bfdcdbb42b80f5f1c4ed7d87825ce53bae639",
    "zh:112221d98fae795d89e6a0adc526fbe2a115316bd052fe10433d93061183b5e2",
    "zh:1487c229ad673ddbd6c46ac511985d9a7ce86120ccf1c929acacb3761f3f1f9c",
    "zh:2b73e4087cfbf20049240914a02f1344e43eb96a3c7d734454e4c49875aba1df",
    "zh:3de5de4e50e58228f612fa158577f623c3a679b18918f62e6b0a925b23e4ec04",
    "zh:6501c980ecb830728929798848105b27ce1cba1b604745fc609ecc54a80e0bd4",
    "zh:67db18b88e93520eb052c5fae1f0dbedefe8433692b98ebdd3e29c3824ef08eb",
    "zh:6aa9bada1a35dd1eb1a37e0233a031d8ecc1ae76ead3e851419bc49ce0dd67ba",
    "zh:80e499f1971e2f5dfa7bbb4c40fa2bb303d6c0752b3d04f9a6869b7051071913",
    "zh:93d63aee4fbacd28eef5330d517f37da2ead51dbd9c1d89e3e2a19a158c15a5d",
    "zh:97c9d6971915400300f78300b807470c00793068b2b90506463da96cf5067092",
    "zh:9a626f4c13f32317e8b891950bfd34eb69970599b9e8f62a5faa565e8c60f962",
    "zh:d233fc2f7173db3ce5de21dc17e37b7757956b48783be3a81b8d92a6893a4fbc",
    "zh:dfc6282c33ab4747d899915027de314687c6f8b49b7c95cafa8544bc45a0d15a",
  ]
}

provider "registry.opentofu.org/hashicorp/local" {
  version     = "2.9.0"
  constraints = "2.9.0"
  hashes = [
    "h1:1dtKYW/5a1qob3yneL6WzOlnSGfYtJ6a2XeejCk9yb4=",
    "h1:5NseXq5wU8O20ersTtV4ocrLYFFtgFr7n0pRLO1W2Rw=",
    "h1:5d22ZPPK4iiygPbwRz/PJF5Es/0axVpMlPRpCR0Padw=",
    "h1:AnwyolirmIlBMjH6+tV8bKkvT+5axJNYxi2y2IguiX4=",
    "h1:PBp+HeseY021Fw3sLznCG27idgwPoff4cBuNmKgPL2w=",
    "h1:VDxIhe4GbzdOCdmt7mQaqdwERQW6GSI7Roonts42Gr0=",
    "h1:ZO6eWWnf8LjjV1q/JNeL9WLtZ6fwIttOnyN5LjCNSEo=",
    "h1:dPIAf8oUAz+vW2E0iZunMvpuPddRZIztRsPSY1u+VnY=",
    "h1:fwTDVG9AhFVKQZIb1EXkHv4FqzsZNlLWgkyPGDmZZEE=",
    "h1:kDc465XPC7/6XFCjrMC4mTqhA9ef0FHKuJ3ZgfGNfeg=",
    "h1:kGbjxrI2P8MHeyVtE1U3Q1TbyF71ExnHxtkrE+Aj6UU=",
    "h1:kcoK6Afbsj54u9zaEqpecWAFKytqjBijtguCNwV3d4M=",
    "h1:rxomJjDwOo+YZ+WIPc25FqEgsz9orh/2MCyUcZmFjvw=",
    "h1:t0CMn/Rkwquw8l2yQ+O4ApzbMZfY2UazbsDnZygzACA=",
    "h1:tJwgm2BS4xCGlElCDQEFXQoefY9Y4t0JdSKTtsPBbBo=",
    "zh:13ef7ecd1e397ec5b20ea588508dd3e3b8d6c50d809ae76b079abf9dd8d02e4b",
    "zh:2190c9325980076489ce02b0f5dd2c0b91fc8711cefa99e714d8619a32827ad1",
    "zh:2a0cfc5600730093705071707e4a4e4e953e7d9091859e0f66b46daa1060dd5d",
    "zh:2ff53eac1af43ab9a2248a0e53c963d46e19cf04bc4c3f323591cfcebb218252",
    "zh:4ebc3dee700f60af9da29970052fd02fa947813162b224716862dc9d7f1f7542",
    "zh:5fe6dab84ceeaa8eb3f1567c5f05578333370c472240ca5c5bfc25e92d4d5586",
    "zh:66bbec16367bbf440045502c9779b11f4ac5b022c8d8d17afe12d431950838b5",
    "zh:7641e5c2e4b529e869cde29ab5b1de2fd1091489eb745b19ac2709bd7f4dfd84",
    "zh:855bfba0756d17ce07595ff57d7cf664443d1495127cb88fb063362734b8b22a",
    "zh:aaec10f237921d60c581d1b7a66f0a8a8019d9802dc04af11b5b981f6682e01d",
    "zh:e460835a38ffa1e74f6929904bfd14ef473d217fd537b7ce834abe5ce5e2ce07",
    "zh:ecc4295215db0e4aea3c9329611c31e09a853e1ae207d56742403bd4f5516703",
    "zh:ee6d9fae63a612072e00402894e14826af7a3351c235b9c5b423b7629a77ca29",
    "zh:f2b5c8db74aa7ebcf7cd423672358437d42401675069ef67b01ff910054e49d5",
    "zh:f5aff74d3eb96d4592c7bca5cd3ea89b469e84efbf382944bd0f844a57059c09",
  ]
}

provider "registry.opentofu.org/hashicorp/tls" {
  version     = "4.4.1"
  constraints = "4.4.1"
  hashes = [
    "h1:2O/yQw456tbotLB9hQANgbHXbIrEtDLSEfgA0WmJkJY=",
    "h1:57BA7JoEeTaNsrQsUXJ/dBBxldjiemEMucc9JuSye0w=",
    "h1:5XqhGbxVrOSEH/sJ2+ZIHg3KvuFR3at07VUioTgkXAY=",
    "h1:Asqo/HjFVO0JSV0VSLwwvtIDhlgBmyHrC8QcO4gk1QQ=",
    "h1:CvzyAg0y2du7vBApIK0N2lPgBaH/zfCg6zm7AwFHpFo=",
    "h1:D6aS7Hmd03IO6vEu3MrPjUKShJOXbRfNYKah67Uy1ek=",
    "h1:EaIwoX0Wc/QXIQdJpIgZKHeSXZ3xjov4l6TvgQseMe8=",
    "h1:Erg6A77uaUPX+2xeS5ZvkZf7kzXUqf7viDsWTd4wXME=",
    "h1:Ku3mHvQI52bhQlKmN2BZI5j7C2VA0+wIHAd/eSufBqo=",
    "h1:OFYWbbN/qi0CMVTkdbzSagb36iEMHJmiCF7hp3hbGT8=",
    "h1:Wb2qBa+YycnQyFzcuSB4aM6stW1pw47MJ6AjG1D6JKs=",
    "h1:baujCERitgMHQWiIU3zCe51pcIBIeod5I50eweY2hYc=",
    "h1:sCAoCoH4c+aLBniVYM4b7Yu1ogWl+pjJOFaQVsR4kBw=",
    "h1:sVCVp+owtzpdcYR2b993egt/nwgmBjOLMosfPpx+Oo8=",
    "h1:v+wMAi0MNFo5N2EtA0GXH1nLns6TAMp7y0lO1kqKWTc=",
    "zh:10daf7d1904ca89d4e54ca39b9a7710a66f2b961cc153f7859c9d5cba6a9cdad",
    "zh:12883f2560676c26431bfe412d4d23b77907c7a994b32c1f58b929473458acaf",
    "zh:141fa1c208a6da9bac474d2f2019cbaa24e1dafa8d834f246b02276e48091657",
    "zh:35f443ce8336ec9a17e5dc7c849b9300fb03dc66ca4c94dfd58a3ee5e3303afa",
    "zh:365a18dbb8b64be4c1a898649eb3777cabb50b7d7a1033aaa11ff93ce98f753f",
    "zh:3fcc9caff4fd3b7b4790ad0a2050379d953de46298c61455535bfbeffe93e53f",
    "zh:44013721c5621ef7cea59a40e7dd5f65e52b4d21fde5e3c50781dbe23d58997d",
    "zh:4f67936376c8588c6ecb975b5c6439596cfd337856418611fa5fc11d5ce302d7",
    "zh:4fae67995e02507602139668609cb1272bfc46ca2555af1ae4abea3cdd86c4a1",
    "zh:555b4e873913835c447d2980ced87d88a9d9d000a63bb66703cbf08b230186ab",
    "zh:a4bd01940c70aa15e443d0fe726b293be75d65832b2881b0888df64a04f4bde9",
    "zh:bdf6ad614b3fe8486c058053a33dfd69ebcc17ec8a80bd7ccabdf3ca9ccc0110",
    "zh:cc45d42c5b38c520f3c7e1fef7fee211d697cb8ceae2fa95d4a9d34b80cb950d",
    "zh:e2b9f6cf7b500a9c2030787d1853409f3277cea5d2f1ec954b966d79b2cc6377",
    "zh:e7e769c0fb629e6f84b146212178350dbd277b472fdbc0808d70e16ae92302e6",
  ]
}

provider "registry.opentofu.org/kreuzwerker/docker" {
  version     = "4.5.0"
  constraints = "4.5.0"
  hashes = [
    "h1:4KE+KFBAONixgKSdhBaDnYLHJ0TVQk6M1alc2MDjfU8=",
    "h1:AN6DBpZM5zELDWEW2HmkTMx6CjQj6MEj/6Vr9Kh4FOU=",
    "h1:DqsEq5W+CcihgDJ9klRiC0ptJcMkObCPG2O2p255pC4=",
    "h1:FF2Hb1TLU+YS+lEmLlWqhEJypX+lsHnQCeAPabrfp2Q=",
    "h1:JSjNIO4XnL9XBHET0+IqQL0eZjG5jws1nvrvgqpjdOk=",
    "h1:KktPg4CVxblNL6RFlec+D/HNfknai8VrqCCs0/ZtkcI=",
    "h1:P2g7oxm45YzbjbjPs1fP+llxPwiX10K4cxCRrQtAL7o=",
    "h1:Pg1C4Rx2kTRhANQwaW/BI3cSi4YVMRPLLI+1CY4gd2Y=",
    "h1:eEoOCLQ/iZIaAO/iijrd0fw4DXvSV7O7awX7qCAFuS4=",
    "h1:eXPMxNcZjz5gC7Nc1oEPJldpI6B5btbvldjLOgJQNbI=",
    "h1:mEARBnOnl9C1tcmrdNS+79cDiSUVBFX4gnwGEm4UQcE=",
    "h1:mtlP++yCfSX1Gs2L0d1vSv/PmZJSvUHP4sdEwA9LluI=",
    "zh:0ee4e9121632158a9ae1049bdd53c71fd9e06357de915dd193df2c1c55ae8814",
    "zh:12c6991012b5a548a406e1960c323484f95a9538c2522af15ec82f47fdb832d1",
    "zh:19c86ae59ed1e062e8402a49ea842f957fcda2f9689e06ecbd9480cc9bd1e41a",
    "zh:3ac8bc9805acd20c40c0ed474c9f4605aa73b61cf52809e1131e335fcbfe8e49",
    "zh:5a0e70d143759712fdda109f024a41d59d4758b5615378aa21ee6b959f65a416",
    "zh:5d3599285f71cc53c88a5802fa6e2f8ba87b9deea03abe5fe8bb2639e9d95654",
    "zh:a42f573a2526cddc9b8a93637a2c5478bc6e903ff29556ab8b2f1467681d5bde",
    "zh:c8de50d902cc8457e565a5d959f1e3e49064d31c2f14f7adf5f3ec632cfe3695",
    "zh:d40543d51eb4e902125d2c5a8a0f425a60edcec6c1dc07c4a89d92335ec05541",
    "zh:dd3105018ffddc8114083dcf84798c32fdecca7ef708eceaee49eb4b306fc061",
    "zh:e51e0199700698b962085683af4551d1f982dce37f3b6950da062c65e0145505",
    "zh:ffe415d3d3deffffdbd3a7173e3a9f90b74601cb6d8acafec1ab701a5b91dbff",
  ]
}

provider "registry.opentofu.org/tailscale/tailscale" {
  version     = "0.29.2"
  constraints = "0.29.2"
  hashes = [
    "h1:7D3VzQoUKr4NYJ7ZMMRdV9iQUK8d6yJBrnBhi0DtBfA=",
    "h1:910l+uQ0y8nSWPo/CsGI0Ni+lM6oc/h6yckucLmivAY=",
    "h1:IPFMdH5vsXeNRj8H/Y6Z6iq3Fko8zkmgcROSXeRJ7MM=",
    "h1:KG/OMAOors/W0AZlHkcUD9aeGBIWDCloKa652+JlATM=",
    "h1:SSZ93MdSAaJ1Xi/VIvZDz5z1sve3BIS+WqDKACvJut0=",
    "h1:Vzj5bDkG9nOQbRMKHPhsol0+BrvzZ22lwkbLSIs4ycs=",
    "h1:Xjuo1Cwe065i1qJfhKm3dti4eeEwIT9rNNqU3R6id0A=",
    "h1:eADNOR3ZnirZXCP+3k0hy9CKQK8sgeVC0lpo08UntZY=",
    "h1:gzBWWbJc4JOwQEIINtnYkbwErRkA2oLvhtRW4lAQ7UU=",
    "h1:ipdqf/NJpSaP7em0/+n3hu0KVzwai3cIn2VgP4Rxdhs=",
    "h1:lNitoP/DTekzHnRjZ3RBLthPRZ3aHy6lR7jo2rtoH+0=",
    "h1:laqGsqlHY2/R1JQnhniKwcT0U8gb+tF0K9vr+Tovskc=",
    "h1:wUSb/6AFeFi905uIodIMA11SyyboCTtDqqNhJYdHweM=",
    "zh:32b453302a684584198a03c2e09d99ef1f6deac2fe26f8dc134d973b07fd0c23",
    "zh:3920bb891a476f30e29248533f667a507c97e93e0a2af010b242e980d6411ca6",
    "zh:630cceb40d8806945ad36e04517f313520ea5cee17bd36e26a8e999567835e1a",
    "zh:6816de7f6bd3cfe341451af3be95b0af17c5539733b165f7505e88de6b730fc5",
    "zh:729d75ab50efb675716ffa609358f6d9e80c66f7f64e01e11c8926c5293385be",
    "zh:7d1024f621fe02b3731dc65ab20105150762b29df46e398da2c73d007bb62fb2",
    "zh:81cf9cd23a70e5196b9d774482259c17e08471556932c348d3e9df0f7a482af1",
    "zh:8de75b9c4b89ed1affcdb3ce32e00afaf213cfd76e93181ea4758ffd10b6eedc",
    "zh:8f0b9b175ceb124c1cf01e6bbb660bf1bce0ff77416e026dc0679ed7156bc737",
    "zh:8fb4cde10eb346ef9e2233591d75c39bcc2cafee578b669196192e8acdb39f12",
    "zh:96798e58b8fcddc2add2da0fe8f1df9f913153d4cbccd68a7557b64633f5ea00",
    "zh:a598bd615f4465b828f3b6ed2db694d8148c9469d5497922c7bc17c08b655cf4",
    "zh:b2604d5067f3f259ff9be9bb0c4f9ec801d27c905cbf6ceafee50fc2a23f8331",
  ]
}
