# Generated by src/bazel/module_deps/update_tofu_providers_lock.sh; do not edit.
# Regenerate with: mise exec -- src/bazel/module_deps/update_tofu_providers_lock.sh
# One `tofu providers lock` block per tf.download mirror coordinate in MODULE.bazel.
# The tf extension fails when a registry sha256 is not among its zh: hashes.

provider "registry.opentofu.org/cloudflare/cloudflare" {
  version     = "5.27.0"
  constraints = "5.27.0"
  hashes = [
    "h1:3m8NMkPCgRpG7Vq6khSq6e4DFy912/QstELqC2LTdZc=",
    "h1:7aAyZL0SdWmVAUvmZzFeun6xe82y/z29nSzTSmkuOXE=",
    "h1:9YNVP8ZdD+Pp5Lu+oJ7AmXMNZ5gnpYgwEpGmcfpwSiQ=",
    "h1:BXwBsvqti6ksI41DfhrGG3myGhPapqYYuCZBYEp9G3E=",
    "h1:V5YAQp7xBX1ExB7x8vQvDMV1M36EoCNXPN//yiWgO+o=",
    "h1:dRh3pOxWvkd69IrxOpIhp+pIRvLLQmPfsei6XBdq56A=",
    "h1:emwSQj4O9ZCnGMfi2/AUMiq5dD3iQgMqnlLPVOqfoCE=",
    "h1:hBbz7uxd+0ZmaFyFm4wBEhe0WkZq4tNLt8wUriBysHU=",
    "zh:0af697c42fc9c5c7359e9209dd2502784789d07dd803ef8ed0e9e1dbc0aea0ff",
    "zh:234be996462aaa9556e024f8434c238cc70bd84960283a4a85d0e096efd9f8c7",
    "zh:56220ac018b93fcac2ad249b668eb9699f1a1f32970eacda05970e3710f8b5d9",
    "zh:7323d107b46ddb1456c2f1d939eaf28e81376203de482d15c1cfe1881903c96e",
    "zh:74b61025e456b944794017ba6b6040f478149964a45f5d328d1dc240b43b8153",
    "zh:77e1b14dd89dd8d6574db4ecb1a5a313480bf1b2e2c29aa86c4f864aa29f74cf",
    "zh:a7893a8def71e5473f6b462accad02fc7f0f842caf03bcd49d3443768d78b9be",
    "zh:ae47a9f29594d57e634cc0b5b96a18da5a364f43cbd735622ce5fe808728065f",
    "zh:f809ab383cca0a5f83072981c64208cbd7fa67e986a86ee02dd2c82333221e32",
  ]
}

provider "registry.opentofu.org/hashicorp/archive" {
  version     = "2.8.0"
  constraints = "2.8.0"
  hashes = [
    "h1:4a8R2WlgZ3LUBXqR2/LqeAu5Q9Unjsh1jbc1XLbQW2I=",
    "h1:5Rcf7ostJMCWpo0EYrldMu+Fq1T23ldisLXGfv4SZmE=",
    "h1:9/wf/bw1G76APmrMENARfP++S3kJGOdOu1gEUmZHaag=",
    "h1:BEA9Ass5e0tn5f8st/h+IxEFJaeocRtBTW6VcGivBJg=",
    "h1:H84fIYOLWMtVduFn5q3HlkSR56SIuM/8rJCZXFc8ckU=",
    "h1:LbnG2K/sbXn52fdEjztAKG4GOli+G/KgadD4XHyaTlE=",
    "h1:NTDoNvS6EccEDIhZQUDoYVOpJz1HDZ+ZW5abIG27YjA=",
    "h1:PjxW7g7rSqZQtcHB0YnvZpdCocPMw9w35pAWEcfLY9Q=",
    "h1:YjAw6RUZ6UxWgLaWf58j5LjzvPuuNuF4/pxD+yqkOhs=",
    "h1:dk3u86A+/wA+2tPJChUgPFJV+r8ow+55Qyh7wTth9AE=",
    "h1:gl6Z86IQ2Xxix+19cfsPJ3IKwXCs+vqA4MqLfTG/vtk=",
    "h1:hct6U5rz1ns287sMtI1b3xGI1h84CXRb0ztXXvN+VKM=",
    "h1:lCfMh04aemFQ4cAUalcxAprp4mVVsgd15Qs84FIAbX0=",
    "h1:npbdnq+7TdLuorM4sjQ5MCpgLZ0zX2heIqjdo+FhtqI=",
    "h1:xS7wTQ2aqTXwvLCZcXShHcVIlpziaZh+5/1HMUHrizQ=",
    "zh:0b8b21e163dd07ee92aeb8085b6c47c0226d8dff7f0a585c042e2050743102f1",
    "zh:40afcd5d2f4e7d4a10ba053698ea9981170121731bfe90de78f907e159c68f72",
    "zh:59be391e1362e8249b3bbebef28ee406464926330a32a10e7e984dd957070e15",
    "zh:685f07c325946bc533d68143dee789a32d0f5c1b3b88c6a8d4c96d8a74b3632f",
    "zh:733cdc39e964d5294ecc1a7d595d0d22df97e2040c0a85ed17fd352487cbb51b",
    "zh:7e100b9dfbfa0eb295921eeba0670652b04de78f598c1f77f0f0b47868373e5a",
    "zh:8c1e6bf711ef5c96ff81923e51b075c41710b193fa3625e3c18d4e8ef629fa9d",
    "zh:8dc06ee505a94f85479c946fe9ac496a93ee6372b8c7747a19d13efb19d337ca",
    "zh:933c20fd5cba9016b9659add7bc2af80c8ef28e80c1bf3bdb4742de4a86f2bb4",
    "zh:939709283eae390ee3e790e94ac8a5c5da555bb59addd0281a33e9a88b1ec697",
    "zh:b713c8b05018a9f20a03d33207c3673857c21788639d01ce4c8752b92de83527",
    "zh:b7ffa7c816458adff82d4a3cf3c0eadc76122a54be2c78667ad3fcc33ca5544c",
    "zh:c1d9328d8928a43c182e09a5f8d47669e007911639bec603360928f70c74e61a",
    "zh:c6f4958fea5f69b23d408b50e7d40ec724cd281f6327a77d5335919484561ea3",
    "zh:c9356b8c980bbd1b702f6ccdc11e2f938b0325e99869b022b58d5299153ea65e",
  ]
}

provider "registry.opentofu.org/hashicorp/aws" {
  version     = "6.68.0"
  constraints = "6.68.0"
  hashes = [
    "h1:0WlqhUcG1EBpy1rHgskjSF+6KZ613LzHY+uedO8YgUU=",
    "h1:7ptaN5PjBGHxx7c56yfRF8woyZ+/QuMEkB4BiIT19vo=",
    "h1:HTsa97lN08fK+M8X/87zDeevZWGftTJm/DGY1kDtrjw=",
    "h1:IU2H4fd2DZsEI48GHDp9hS7DQTAlN+8/9JybpARKM6I=",
    "h1:J2U80DNxn0qzM8EwHTzYaXELx7M6OjtrPA8sT0Fi/1U=",
    "h1:W0v5vKyPNcILb8i8EwdSH1YZ+aPrh990xTfJra/m80k=",
    "h1:XcxlVePKXLu2vkJ6CaeLE+TCgKfNzNjgOFvgoPX0mvY=",
    "h1:bCnv9rG4RV5edxG9Eb5pEiDhlqbMXUCQoyuxaCfRXW8=",
    "h1:c9iZNPOAuhLFs0ABsE/HEHAdbeIGsb19URzt4FFyRoE=",
    "h1:dOfTYF4QPUscl1xyGeON0qpI9Utgi1nRAgOK1xXY07o=",
    "h1:dxCcRKyXJ+PeP3zwshWgucc7RIlYtctCLswRVXpVoyM=",
    "h1:it7nE0v+/rI16Uy8fn39llogcMgBzLbDDzhyXA1xzR8=",
    "h1:rM1kLzeiQaqKkBS8nrCXvaQyS+hhWrjEM0oH5NY2ECs=",
    "h1:vJumJC1FSHkKE0UrFw9XsR1y31yXy0glabZw/PEkeOs=",
    "h1:z6IwGoPuKMbCbvUupnKdW1+CmT/QdAe5MRszMhtFaLI=",
    "zh:157cf5b4c774e8fe87ad6392d03b777f5143b7b620e7cc085d2d5ba52290dfe6",
    "zh:1c1f5e764c46b6f7118e358680720c73b0ce291b9046db8a654e7cc2ba028f29",
    "zh:3abc93e114713c5ebcb761e25ce31c01d1f75acb3c93a93d25a16579352bb8b0",
    "zh:46dbf26387a599ae542eea728a70442746a4813da48022a2d0346b5127997c57",
    "zh:5f5baa837d51254036ffcd3ec582a5933b1891299fff12e42905ddafe74f4265",
    "zh:64e0d39cca5460b44579ac2bf9004aaa804c6c806cb4af0f57c0194851538728",
    "zh:7f82485b713c5046010cb53adb5bb26e961cf428b9f3c9b0c33f3ee31ccd02e5",
    "zh:9ce9b391cbd4cdffe2b90399924670a1f4b5fc56cbbd52c47aba594c791f6d4b",
    "zh:9e727c5276a30e5c47ec3314f182777ded0d5c5240412886b6403adb430bb2b1",
    "zh:a1b328d08cb3a35c33dae78d83f4e434b098e7311e88732803682939f0b24be7",
    "zh:cd498403911976b383d86f8191ad236e4acef84a43171125b133edb93a9b6b8d",
    "zh:d2de56bfee82aa28316b9c56941941325eb9dcd4684bce4756d1969d1a939013",
    "zh:e8aaf5ba22d79839e2ddeff637e9be3d4a7be98a002a12c99f02c1b859ac8d39",
    "zh:efa2e3fc537a965fd0bbbfebed9d38ee49d37277d5012759b748f945c3e26ea7",
    "zh:f5d1220eac0f137a8408ca40c8c6ff5b64cb94d271add882a377bee6476d4bc0",
  ]
}

provider "registry.opentofu.org/hashicorp/google-beta" {
  version     = "7.45.0"
  constraints = "7.45.0"
  hashes = [
    "h1:0+Q/xe+Rgn+X6i4C+pmDOqlG4BheYLAzvg7s2KiHD7s=",
    "h1:2diUo+hOvjnxaXAI3COykfISwOWd0XUt4FBev61byNQ=",
    "h1:6WcVToUwdrgYi7T9epn7KUgpONxypdSlq1BATDNxqDw=",
    "h1:BX0Wep2JLmnozEyjXDg48UlQLd7FYjQv0p+PSOeVES0=",
    "h1:Dg/Z4CDXVla0iz3BAFSLxx12d1akT1eCmCbkyxzNNEs=",
    "h1:EjE86Yc7EGw1CiJYlIJr+2AdDlkFBvtDybLrG1f4wqc=",
    "h1:HOJrHl2VNU9kMfwn9Pbge4Sdu5TMrv8jSpvOeG+Frpk=",
    "h1:OolSd0g9iMcCpcufdi23DI3hVLjw8WmljRzeBDaVqIA=",
    "h1:XhlQCDqVSz82InFGsyZPxn2HrXK7p++BPDLsAVKqIOQ=",
    "h1:db1kzZHhS+QpgETybHMUnsFRKpY3PFK9CQze2MnYgjM=",
    "h1:dyaoPU6mD2woyTDIeqp1yCAUPcM0ORDye6JaGnhnz/s=",
    "h1:mxJoAcPCJomm43WcxtrH3XnrSqbQbPU7BaVx7F1wEsM=",
    "h1:tzP+P9PeZH2y/+8f3bDU9bjr7lbV5bU0diXGIcj2+IM=",
    "h1:woE3LHWktlv1ugztMXJ2Z3joTaByjH35SErKIEvR9Zk=",
    "h1:zR1DYUdD2JUiEh5E/xYSzfmBH88AxBuYs6mOHoKsyWU=",
    "zh:09535cb193fadf41ca5957e28a93ce622407ee8cd6f7ae33d4bbf8695530ea10",
    "zh:0a7cad8112f9c7fe006bbbcffca6ab26cfd4b9d04d74215e904f8ab67ff50f1d",
    "zh:0d17b8d2fa04fb029d74fa613de55af9230854ecdd6b62cfba0051a876c8b024",
    "zh:1c3815ef5ca1831c9efe99c8e961abb15e19fef8fa596ead4ba504138e45b4eb",
    "zh:3a5cb54bf37083e7a08f131492f99f4bcd902055b3504d4ec0a207461f8cad6d",
    "zh:5c57a34e0315bb72e41aa2f96c3f8a9690e9be83aee8fdc3c79ecdf066e7498c",
    "zh:6378ee766c094b1e6a8433bf54a6e7559f57954c8ed32d3103f1e910ea97802f",
    "zh:765b720ae1eb635837dd591f4a4c6b2915618157aa849a7243705780bd324d6a",
    "zh:7f62971e8e2009518e6f7045a863d366697f9355b2917cfe7471e746fd74909f",
    "zh:a3212106b964d5cd10f9b2fdd0ce7abe60849fb1a16b57f9aa8a16102e76577f",
    "zh:bc8daa2508aac6d1b98c3774f1d20d96ae6aca507f938a68ce86affbf115a1af",
    "zh:bce4be3e2e84dd7203d6de92cc1e25c3a02b25f0951c192346ee10d6c8f06d39",
    "zh:c8ab4835ff3c237d9f8ae42249ad4a66c7e07500f3deddd7f0feec547118079e",
    "zh:d09db961306237a7861e466b53d23428ade1fac2a68b896ce0044a1c1c297e85",
    "zh:fada263689d0bdb535e2d0adf7eefafd257f2713b080a65fdfcab1a0a8096d4e",
  ]
}

provider "registry.opentofu.org/hashicorp/google" {
  version     = "8.6.0"
  constraints = "8.6.0"
  hashes = [
    "h1:/X3hxGbJLkRbkVlFiRuNGtcuILxbCOujpIl/EUZbXm4=",
    "h1:0mpLt/Q/B1wRzBoyE+7m5JwWLafn7zCZbCo6/wQRyUc=",
    "h1:5fQMvmlUpca2+bGXNDOGOasyjXLkmXebUytiNywZZTg=",
    "h1:DIqh8zMBg5LA6wAjj5SrQTBUeVdzbo2zighmF97TZ1E=",
    "h1:FOoPkcLXnGMXI/LG4eojh4z2yjSj6fqNOx+/e6U+C54=",
    "h1:MufxGIpsLPFhKSfyoDVO7hLmRI1EYrtq10t9MU0Fy3w=",
    "h1:NvJFKm00N0XCY404PsjsH9DBe43OjGZeUeP/DjjKqqI=",
    "h1:QYXBBo0dgbmR6iS+MqhPmnVH09hpnS6DIdfQssqFCIs=",
    "h1:S7WhiBgpxJwWUiH3Ic0gpTbd6Qol9axTHYHPu2vhaHE=",
    "h1:ghMuYHy7+7+4axN+PAx/F67/kggSzdyZFKWIuwTyj+M=",
    "h1:hBSA5dIkbvzOCb7+4Hx36QEzvRDRH2m4JgwqPOm6dyQ=",
    "h1:y4X4zRw6UbrMtEm6sJ8tuG68mlgTLnsr2SnV64n9bzU=",
    "h1:yZvhz7ObvS0LN/g8ln86oQVh98WmpqS02MTozj8d+/g=",
    "h1:yohq4HRzKL0B64RIXb6L5ojPy7kaSs8uHOQi++RPS/Q=",
    "h1:zm40Oyv3DL0Vcj5+MslRSlQJ7u068B3NkRBhgE4QOXM=",
    "zh:01c5c4f1d024a81f24e3cdfaaa693f5f4f50f6d34467e5aa01feef10a50c0571",
    "zh:0b65c54a8aa1c2033110e6c1a033dd9f19bcf530a4872860e7141892c8e58913",
    "zh:1c09bd3dffa27ef45f2c1474b507ff3d36dd122debae331896fc8ec75c9fdd65",
    "zh:39c3660e1285e023f251d1ef364602e0a1d0fc80b0b74dece809666d54ee8e9e",
    "zh:60f755fda3d0210588a09c69960a1f06073f2f3fce9c7a6146f21276514074c3",
    "zh:68a0a4a0e925bc579f4572619b2efae54b4ffcd5cd192e9265c21cb4fa4ba5b4",
    "zh:709cf33897a92cc8e4aa02933490ec844bc632270e72dea4b9ea32c3a7f15483",
    "zh:865afc643b24809ec17df67efdf36c3017e9098b78b1dc617c63f9ac81e90e54",
    "zh:9a7ffd4a090379e45c5366aea028837093b993ddf7737238339f95b9987f54aa",
    "zh:a4c764cf418fa335ea1bc9f2684f92e695e15db395d8f0f7a3a5e80bfef05ac0",
    "zh:c4fee1a7b5fa5d91fef5aae16f95ede19654af7f2a07415bfca79a6534e77c2f",
    "zh:c51b8f433beb6b5716086e53d84abe608d0e2ecacf405f955a365a8142a48d06",
    "zh:dee59323983be461ceb4cbe9f166c2cc600d15b4157f3b6ebaf3acfc8f7a108a",
    "zh:e1b37038d951c67444e5aec86148609f1ab06989a66c32d03b6135df5df20a3c",
    "zh:e2d038eefcdc59bdb19ed408d5af818de4405cb9334238d833d33024d8fc9d80",
  ]
}

provider "registry.opentofu.org/hashicorp/helm" {
  version     = "3.3.0"
  constraints = "3.3.0"
  hashes = [
    "h1:0zhsz9jzK+UxFNFYNJN904Hq1QYs9VMG4xPSumkKw/4=",
    "h1:3iVzjHzAq+YMymNbTq90zF20PeZu+ds1URRxhnoVRpg=",
    "h1:AYVZH0uO00tVS2VIMWfwTGkX+d1aloByZBbhdcDAxIo=",
    "h1:JJ9E97HlAUK2JZ/pdi0UZxZgBlNDq5dOjzrbLW3XK24=",
    "h1:JOepgsqVn+Fw+fY22j3hnA2Lj+W3S6RxPxPqokWJVAk=",
    "h1:MoUoWd56qOteNNVkYzKK5u5j7Xv/RAknMvZtm6PcTXo=",
    "h1:VZKsnRruH8EJRbgNk2jyTSPCYivOHOC03Q0JcXolLg8=",
    "h1:flPd03Uovsfo0ldt4rR17W1c8ibj2r7HQj+wGITWDGY=",
    "h1:hTuXyyFZQu7lIWRi9gjInX2OOcDDTuizLXWaX8fcE38=",
    "h1:jDTdMgfyGpYXyB14FI+Rqtf0A3HEDzYflXR2AGSOv3Q=",
    "h1:oR85nmKV3TSkBglrk77YaRcM5blLF6oeAqQZ9togpTE=",
    "h1:pH8KpcaZHzKxA2NQP7br0ap141z+G/mPwi59g4ozxHM=",
    "h1:uqQPsBGF0vlVz3WoResFm6AbJETVR0Vk+RMz+xzScuk=",
    "h1:xuZBFcoqxFfL6l20lS6fKVc66QPWQ9KFPycnvPIVG5c=",
    "h1:y5ZruUQcffAeqCU6mV1vZJYl96ijHc4GsQno/fOQ+Ng=",
    "zh:0a406aeadea91aa0feabd73ba27fe125f61993dfe760040f8bf35e3500b23e58",
    "zh:0e0c15a255c16857afa88f1a799496eef11db0815b4fdceb0902483a96c4f14a",
    "zh:29e894f6d09600a26b48510dac208f7742459f041ee6f640240f6e707b50591c",
    "zh:2c8cb4f322eb11396b053fde8f6e69cad689b46a15bddba458526342dae566db",
    "zh:330a3fe4c46175ffd5c9235d0337928fc2afd983020a0e1078a7ad74703f1852",
    "zh:44b37c8b20ae57eaca35e705625f97f9c1195915b2ef94b6d2890487cb27fb46",
    "zh:465aa9cfc5bc2e2e00cabb28f842b387eab58fdc44133bec7b9ee33f13c0adf0",
    "zh:5ac37a38cde4fb446f12c6ba8d8d775e0969f52cb19b6050de3c13f68a7c2374",
    "zh:759ededfe4245148acbc013da37fd592983ea1f1cb563d1b7c7a333eb2948654",
    "zh:84ac494bd529498b088bb6021fe4bce5ff365ad3468e6bcb5fc9fc8eed287437",
    "zh:88202f2941b795f4ac9e02ea1e6301f462778307eb3b39e8950a6a05fa2574af",
    "zh:8ddd111d58bc19bb9787093b64070238ce1d24cfaa63530456154936564135e8",
    "zh:95c9c38088148054bf3e9c7771e4a40f03e1c384084462489170a34fdfab398f",
    "zh:a2ab783211d5ebbadec3341618b565809db872eb61e0aad5093e38e2c2cb047f",
    "zh:a8439b77862dfc9bfe0c43a0710ac3cbcd113eb50e5cad3f8a78f2cd1ac11baa",
  ]
}

provider "registry.opentofu.org/hashicorp/kubernetes" {
  version     = "3.3.0"
  constraints = "3.3.0"
  hashes = [
    "h1:24nHiQ0TNv7Hxf2VRQSgcrijZuoZAC6NVsgzoON/3aw=",
    "h1:8lQbwJxPR0iCkVL6mnRN1snYy0ajRNAh7U2M0od+jNU=",
    "h1:FfbE7S9CaL0JV7bf6X2PmaDMjmwlAx5FHFcVRqMpikM=",
    "h1:GSOodbfyyqXi9s81npPg2/uMMJVV7d4lt7wcuCNWGLA=",
    "h1:GgNCI1lpHVzkEkmwv50aQlfvzVqrghKbAy6hLZ69yDQ=",
    "h1:SPuYJHuV3MflvF+dMtKYAL+U2lyuB2C6zGO7AIH8qd0=",
    "h1:XHzOkEN3d10bftax79PFVEijifcFyoB170n5kENAD5g=",
    "h1:cCyiNa/BgpuJwzPs5Ndv8blqPSqXUZfTtfheJHXAMlI=",
    "h1:ihPBOnYN19cLR0RtZhkOnACRkm3MUbaAIYa8pQYaff8=",
    "h1:jqFDTH2MrgbP2QFh8R3uF+K8N6HakdVwIu9oKDnrw4Y=",
    "h1:lys2oGVmSEbRKUX4CAldW2ao4BYPVQivbozS/IjF/ts=",
    "h1:m3oeCcjqh6C9PPwIeiETvcD6tFxL1Z+SXEZ1nQscIiU=",
    "h1:onwKIo6p8yMxC+Jroxj9vvbApXU7A3uoGjfsdcNS81k=",
    "h1:pb1tkWZx2qBorNFF/nQqMjAJK4g5MSJG96VLPXFRP3o=",
    "h1:tfpp5qfpHrwBM1vm0sQGrmY6vbOQGcnXAfsIhgcgB4o=",
    "zh:2278bd68c7ed7aa9f8ea1403ccf5d6bc8a6556f716b5fcf0cf1063d38b7a3f09",
    "zh:4492d8d3bf6adf097391efa5fc4a9cbc5b778fb33569389ec2671930f7ec1b81",
    "zh:503e928c9baecf55a938814a7202980f3cf56aa38c650b66de8cee680619afa7",
    "zh:6bf16df25c0ae5eafd4342e8a86a5610d7de5d51bef637af69ab6781b639f3d6",
    "zh:734f4350e6f5310e6c559f8b060b16b1f7ab80806db2acd6860d0ad41e371964",
    "zh:746f332e95678e528a6b82af68e3fed4558ffa0862b47dd23a7dc460259e6334",
    "zh:810d8bbfe18393adc946ab510c71355a9fa013fdf4ba72b4716efc0ebfcc5452",
    "zh:a90e5570619da2e180f569b2c2bf1a15d537752c0573a5381c37d9f00e8c7b08",
    "zh:ac8b720a0000b08bca3438d71643908173dde2ace162cabc93597aa726582937",
    "zh:ad762caf74474001c9560801bfac13cc22dce64ebc9810d580398b4f6f4219fb",
    "zh:c37a862c1eb21e8e4722bc004b716569c1a0cbd5be8ef630c9444d899e46528d",
    "zh:d7d2645598c87ebaa4330f4a2a95b6e21918d1c5fb2241501c3575c02b504d8a",
    "zh:da775175625d247d6281a17836fdf0bc44da4a0456c603da6b8c77769a7d629f",
    "zh:ee7f8a035f240c26e56e24a4db69388b53630a199536e1f6459d71d81d0ca0f3",
    "zh:fa8640f12c6ae1ad54cfc24ddd1a70109420678d7c5423e0c850cc5137e6f7b7",
  ]
}

provider "registry.opentofu.org/hashicorp/local" {
  version     = "2.9.0"
  constraints = "2.9.0"
  hashes = [
    "h1:1dtKYW/5a1qob3yneL6WzOlnSGfYtJ6a2XeejCk9yb4=",
    "h1:5NseXq5wU8O20ersTtV4ocrLYFFtgFr7n0pRLO1W2Rw=",
    "h1:5d22ZPPK4iiygPbwRz/PJF5Es/0axVpMlPRpCR0Padw=",
    "h1:AnwyolirmIlBMjH6+tV8bKkvT+5axJNYxi2y2IguiX4=",
    "h1:PBp+HeseY021Fw3sLznCG27idgwPoff4cBuNmKgPL2w=",
    "h1:VDxIhe4GbzdOCdmt7mQaqdwERQW6GSI7Roonts42Gr0=",
    "h1:ZO6eWWnf8LjjV1q/JNeL9WLtZ6fwIttOnyN5LjCNSEo=",
    "h1:dPIAf8oUAz+vW2E0iZunMvpuPddRZIztRsPSY1u+VnY=",
    "h1:fwTDVG9AhFVKQZIb1EXkHv4FqzsZNlLWgkyPGDmZZEE=",
    "h1:kDc465XPC7/6XFCjrMC4mTqhA9ef0FHKuJ3ZgfGNfeg=",
    "h1:kGbjxrI2P8MHeyVtE1U3Q1TbyF71ExnHxtkrE+Aj6UU=",
    "h1:kcoK6Afbsj54u9zaEqpecWAFKytqjBijtguCNwV3d4M=",
    "h1:rxomJjDwOo+YZ+WIPc25FqEgsz9orh/2MCyUcZmFjvw=",
    "h1:t0CMn/Rkwquw8l2yQ+O4ApzbMZfY2UazbsDnZygzACA=",
    "h1:tJwgm2BS4xCGlElCDQEFXQoefY9Y4t0JdSKTtsPBbBo=",
    "zh:13ef7ecd1e397ec5b20ea588508dd3e3b8d6c50d809ae76b079abf9dd8d02e4b",
    "zh:2190c9325980076489ce02b0f5dd2c0b91fc8711cefa99e714d8619a32827ad1",
    "zh:2a0cfc5600730093705071707e4a4e4e953e7d9091859e0f66b46daa1060dd5d",
    "zh:2ff53eac1af43ab9a2248a0e53c963d46e19cf04bc4c3f323591cfcebb218252",
    "zh:4ebc3dee700f60af9da29970052fd02fa947813162b224716862dc9d7f1f7542",
    "zh:5fe6dab84ceeaa8eb3f1567c5f05578333370c472240ca5c5bfc25e92d4d5586",
    "zh:66bbec16367bbf440045502c9779b11f4ac5b022c8d8d17afe12d431950838b5",
    "zh:7641e5c2e4b529e869cde29ab5b1de2fd1091489eb745b19ac2709bd7f4dfd84",
    "zh:855bfba0756d17ce07595ff57d7cf664443d1495127cb88fb063362734b8b22a",
    "zh:aaec10f237921d60c581d1b7a66f0a8a8019d9802dc04af11b5b981f6682e01d",
    "zh:e460835a38ffa1e74f6929904bfd14ef473d217fd537b7ce834abe5ce5e2ce07",
    "zh:ecc4295215db0e4aea3c9329611c31e09a853e1ae207d56742403bd4f5516703",
    "zh:ee6d9fae63a612072e00402894e14826af7a3351c235b9c5b423b7629a77ca29",
    "zh:f2b5c8db74aa7ebcf7cd423672358437d42401675069ef67b01ff910054e49d5",
    "zh:f5aff74d3eb96d4592c7bca5cd3ea89b469e84efbf382944bd0f844a57059c09",
  ]
}

provider "registry.opentofu.org/hashicorp/random" {
  version     = "3.9.1"
  constraints = "3.9.1"
  hashes = [
    "h1:38E2VQmQDhws/3AL3D/EzBGuCseepyZRIswAOx8CqoQ=",
    "h1:7+qv9kpOpBC9EUPCubnPxh603tu3l9EIMMBkpbt1H1Y=",
    "h1:CEQeHfnUDB3uqAkKoEWfWgbj+kpoQHgcuPbAjPzbh+U=",
    "h1:HPYO9tf8KUSHqSdz1uOL97MLeaVHPaWPY1JW6tKU19E=",
    "h1:KYXiC06Pr3WJcIUbDq9MgdAbInO5zcRyHFqV1x5UcJg=",
    "h1:MygjbYH8CrPv8RUe75tZAFmrFNIzQLT45fiyYx7u2tI=",
    "h1:RMSARNOw4qZx+VmHYnVMGljsFVfCV1P+nJjKrN2XIOI=",
    "h1:U/71jbSbfsfVLxWpSlhyVHh/DnQXQhjoJCGkyongkBA=",
    "h1:WwLLvRE1q95CTGxyTjKpctXJ0ooVs9d22JAQS9fC3uo=",
    "h1:ZtRBSqoyfQAhngjUjM0NRPtj6NdSJ/JBENFwT8D276s=",
    "h1:cfxedZLduhHD1UtqQDjAQZNAEhr/bWDAZ4nU9rSdySg=",
    "h1:i45mo4de0QKOreStMqUQ7qyZL3ucFq42l178Fm5/hMU=",
    "h1:v3SAJKN4D3dOM95xKwgKGIWELe5nUBbyXdb5HNz7icw=",
    "h1:v3vTk/STekrzNc6NG3jL9/05zhvF1QVCgyRRbvSHPcI=",
    "h1:zHgFWtRBgOycqhw8HdLSvMVNWGJtIjOAPYOcAdE7cL0=",
    "zh:09aaf19b0d22726d2378e0e89fbbefc183494d7bd585759d6c4e69ba50951a2f",
    "zh:31575ca9bc0db20337096d178ea73bce3ebca343ed071c67f78cf39f800c9ec6",
    "zh:624fb6ed552abc34a5aaac41e76a373da65ac08e524b09b672f29c60e6ac896a",
    "zh:6a4760d55132b9750ac1a04f6fc32e247034daa999f71452dba9cbca225a529a",
    "zh:768a6047cfb8958e7b0b120c580aa3de6624a7fbb2c56ad6df85cd559ed26ec7",
    "zh:8983c788ba660bcb587e64ff9c3e4323515caf78facbe0abe6432e7aff8df893",
    "zh:8d570eb026a4f00b58a1d36be0ce3c13adf4d973efcd4162b05cb295bbc14257",
    "zh:a2259540854d5f699c36b89244fb202ebb2c219b64669a51072687d04fb47152",
    "zh:aaa51d905b0e80a28e02f9bee2cf6c91ffade7389d77ab9198aa12809ed04955",
    "zh:afb60995e98573facddfb47baedf7e288408680eb00b5d3df570611758947c72",
    "zh:b9a46d852ce53fa037f47537a7de53f37b759ccf211600b7ba44c66ba4b616b7",
    "zh:bafcfeeefcd0dfefeff120b655b45edb0497c4717534ffe5201b3cb556d1ffe6",
    "zh:c3ac24d397eae054aca2290e20943e0c767592cc661c890850c25ac01829308d",
    "zh:eafba4127ebadcc5ed0e427935c66fb5e2da7cfdaae39a66d52f4a50d51faf1e",
    "zh:f39d4bce213ed9bba3474bad468136af08ff6c4c33adaafcc10c1f78067adfe3",
  ]
}

provider "registry.opentofu.org/hashicorp/tls" {
  version     = "4.4.1"
  constraints = "4.4.1"
  hashes = [
    "h1:2O/yQw456tbotLB9hQANgbHXbIrEtDLSEfgA0WmJkJY=",
    "h1:57BA7JoEeTaNsrQsUXJ/dBBxldjiemEMucc9JuSye0w=",
    "h1:5XqhGbxVrOSEH/sJ2+ZIHg3KvuFR3at07VUioTgkXAY=",
    "h1:Asqo/HjFVO0JSV0VSLwwvtIDhlgBmyHrC8QcO4gk1QQ=",
    "h1:CvzyAg0y2du7vBApIK0N2lPgBaH/zfCg6zm7AwFHpFo=",
    "h1:D6aS7Hmd03IO6vEu3MrPjUKShJOXbRfNYKah67Uy1ek=",
    "h1:EaIwoX0Wc/QXIQdJpIgZKHeSXZ3xjov4l6TvgQseMe8=",
    "h1:Erg6A77uaUPX+2xeS5ZvkZf7kzXUqf7viDsWTd4wXME=",
    "h1:Ku3mHvQI52bhQlKmN2BZI5j7C2VA0+wIHAd/eSufBqo=",
    "h1:OFYWbbN/qi0CMVTkdbzSagb36iEMHJmiCF7hp3hbGT8=",
    "h1:Wb2qBa+YycnQyFzcuSB4aM6stW1pw47MJ6AjG1D6JKs=",
    "h1:baujCERitgMHQWiIU3zCe51pcIBIeod5I50eweY2hYc=",
    "h1:sCAoCoH4c+aLBniVYM4b7Yu1ogWl+pjJOFaQVsR4kBw=",
    "h1:sVCVp+owtzpdcYR2b993egt/nwgmBjOLMosfPpx+Oo8=",
    "h1:v+wMAi0MNFo5N2EtA0GXH1nLns6TAMp7y0lO1kqKWTc=",
    "zh:10daf7d1904ca89d4e54ca39b9a7710a66f2b961cc153f7859c9d5cba6a9cdad",
    "zh:12883f2560676c26431bfe412d4d23b77907c7a994b32c1f58b929473458acaf",
    "zh:141fa1c208a6da9bac474d2f2019cbaa24e1dafa8d834f246b02276e48091657",
    "zh:35f443ce8336ec9a17e5dc7c849b9300fb03dc66ca4c94dfd58a3ee5e3303afa",
    "zh:365a18dbb8b64be4c1a898649eb3777cabb50b7d7a1033aaa11ff93ce98f753f",
    "zh:3fcc9caff4fd3b7b4790ad0a2050379d953de46298c61455535bfbeffe93e53f",
    "zh:44013721c5621ef7cea59a40e7dd5f65e52b4d21fde5e3c50781dbe23d58997d",
    "zh:4f67936376c8588c6ecb975b5c6439596cfd337856418611fa5fc11d5ce302d7",
    "zh:4fae67995e02507602139668609cb1272bfc46ca2555af1ae4abea3cdd86c4a1",
    "zh:555b4e873913835c447d2980ced87d88a9d9d000a63bb66703cbf08b230186ab",
    "zh:a4bd01940c70aa15e443d0fe726b293be75d65832b2881b0888df64a04f4bde9",
    "zh:bdf6ad614b3fe8486c058053a33dfd69ebcc17ec8a80bd7ccabdf3ca9ccc0110",
    "zh:cc45d42c5b38c520f3c7e1fef7fee211d697cb8ceae2fa95d4a9d34b80cb950d",
    "zh:e2b9f6cf7b500a9c2030787d1853409f3277cea5d2f1ec954b966d79b2cc6377",
    "zh:e7e769c0fb629e6f84b146212178350dbd277b472fdbc0808d70e16ae92302e6",
  ]
}

provider "registry.opentofu.org/kreuzwerker/docker" {
  version     = "4.5.0"
  constraints = "4.5.0"
  hashes = [
    "h1:4KE+KFBAONixgKSdhBaDnYLHJ0TVQk6M1alc2MDjfU8=",
    "h1:AN6DBpZM5zELDWEW2HmkTMx6CjQj6MEj/6Vr9Kh4FOU=",
    "h1:DqsEq5W+CcihgDJ9klRiC0ptJcMkObCPG2O2p255pC4=",
    "h1:FF2Hb1TLU+YS+lEmLlWqhEJypX+lsHnQCeAPabrfp2Q=",
    "h1:JSjNIO4XnL9XBHET0+IqQL0eZjG5jws1nvrvgqpjdOk=",
    "h1:KktPg4CVxblNL6RFlec+D/HNfknai8VrqCCs0/ZtkcI=",
    "h1:P2g7oxm45YzbjbjPs1fP+llxPwiX10K4cxCRrQtAL7o=",
    "h1:Pg1C4Rx2kTRhANQwaW/BI3cSi4YVMRPLLI+1CY4gd2Y=",
    "h1:eEoOCLQ/iZIaAO/iijrd0fw4DXvSV7O7awX7qCAFuS4=",
    "h1:eXPMxNcZjz5gC7Nc1oEPJldpI6B5btbvldjLOgJQNbI=",
    "h1:mEARBnOnl9C1tcmrdNS+79cDiSUVBFX4gnwGEm4UQcE=",
    "h1:mtlP++yCfSX1Gs2L0d1vSv/PmZJSvUHP4sdEwA9LluI=",
    "zh:0ee4e9121632158a9ae1049bdd53c71fd9e06357de915dd193df2c1c55ae8814",
    "zh:12c6991012b5a548a406e1960c323484f95a9538c2522af15ec82f47fdb832d1",
    "zh:19c86ae59ed1e062e8402a49ea842f957fcda2f9689e06ecbd9480cc9bd1e41a",
    "zh:3ac8bc9805acd20c40c0ed474c9f4605aa73b61cf52809e1131e335fcbfe8e49",
    "zh:5a0e70d143759712fdda109f024a41d59d4758b5615378aa21ee6b959f65a416",
    "zh:5d3599285f71cc53c88a5802fa6e2f8ba87b9deea03abe5fe8bb2639e9d95654",
    "zh:a42f573a2526cddc9b8a93637a2c5478bc6e903ff29556ab8b2f1467681d5bde",
    "zh:c8de50d902cc8457e565a5d959f1e3e49064d31c2f14f7adf5f3ec632cfe3695",
    "zh:d40543d51eb4e902125d2c5a8a0f425a60edcec6c1dc07c4a89d92335ec05541",
    "zh:dd3105018ffddc8114083dcf84798c32fdecca7ef708eceaee49eb4b306fc061",
    "zh:e51e0199700698b962085683af4551d1f982dce37f3b6950da062c65e0145505",
    "zh:ffe415d3d3deffffdbd3a7173e3a9f90b74601cb6d8acafec1ab701a5b91dbff",
  ]
}

provider "registry.opentofu.org/tailscale/tailscale" {
  version     = "0.29.2"
  constraints = "0.29.2"
  hashes = [
    "h1:7D3VzQoUKr4NYJ7ZMMRdV9iQUK8d6yJBrnBhi0DtBfA=",
    "h1:910l+uQ0y8nSWPo/CsGI0Ni+lM6oc/h6yckucLmivAY=",
    "h1:IPFMdH5vsXeNRj8H/Y6Z6iq3Fko8zkmgcROSXeRJ7MM=",
    "h1:KG/OMAOors/W0AZlHkcUD9aeGBIWDCloKa652+JlATM=",
    "h1:SSZ93MdSAaJ1Xi/VIvZDz5z1sve3BIS+WqDKACvJut0=",
    "h1:Vzj5bDkG9nOQbRMKHPhsol0+BrvzZ22lwkbLSIs4ycs=",
    "h1:Xjuo1Cwe065i1qJfhKm3dti4eeEwIT9rNNqU3R6id0A=",
    "h1:eADNOR3ZnirZXCP+3k0hy9CKQK8sgeVC0lpo08UntZY=",
    "h1:gzBWWbJc4JOwQEIINtnYkbwErRkA2oLvhtRW4lAQ7UU=",
    "h1:ipdqf/NJpSaP7em0/+n3hu0KVzwai3cIn2VgP4Rxdhs=",
    "h1:lNitoP/DTekzHnRjZ3RBLthPRZ3aHy6lR7jo2rtoH+0=",
    "h1:laqGsqlHY2/R1JQnhniKwcT0U8gb+tF0K9vr+Tovskc=",
    "h1:wUSb/6AFeFi905uIodIMA11SyyboCTtDqqNhJYdHweM=",
    "zh:32b453302a684584198a03c2e09d99ef1f6deac2fe26f8dc134d973b07fd0c23",
    "zh:3920bb891a476f30e29248533f667a507c97e93e0a2af010b242e980d6411ca6",
    "zh:630cceb40d8806945ad36e04517f313520ea5cee17bd36e26a8e999567835e1a",
    "zh:6816de7f6bd3cfe341451af3be95b0af17c5539733b165f7505e88de6b730fc5",
    "zh:729d75ab50efb675716ffa609358f6d9e80c66f7f64e01e11c8926c5293385be",
    "zh:7d1024f621fe02b3731dc65ab20105150762b29df46e398da2c73d007bb62fb2",
    "zh:81cf9cd23a70e5196b9d774482259c17e08471556932c348d3e9df0f7a482af1",
    "zh:8de75b9c4b89ed1affcdb3ce32e00afaf213cfd76e93181ea4758ffd10b6eedc",
    "zh:8f0b9b175ceb124c1cf01e6bbb660bf1bce0ff77416e026dc0679ed7156bc737",
    "zh:8fb4cde10eb346ef9e2233591d75c39bcc2cafee578b669196192e8acdb39f12",
    "zh:96798e58b8fcddc2add2da0fe8f1df9f913153d4cbccd68a7557b64633f5ea00",
    "zh:a598bd615f4465b828f3b6ed2db694d8148c9469d5497922c7bc17c08b655cf4",
    "zh:b2604d5067f3f259ff9be9bb0c4f9ec801d27c905cbf6ceafee50fc2a23f8331",
  ]
}
