#!/usr/bin/env bash
# Regenerate tofu_providers.lock.hcl from the tf.download mirror in MODULE.bazel,
# then refresh this host's MODULE.bazel.lock entry for the tf extension.
#
# Usage: mise exec -- src/bazel/module_deps/update_tofu_providers_lock.sh
#
# `tofu providers lock` verifies each release's SHA256SUMS against the
# registry's GPG signing keys and records every archive checksum as a zh:
# hash. The tf extension refuses registry checksums missing from this file.

set -euo pipefail

root="$(git rev-parse --show-toplevel)"
lock="${root}/src/bazel/module_deps/tofu_providers.lock.hcl"
platforms=(linux_amd64 linux_arm64 darwin_arm64)

# Every "alias": "namespace/name:x.y.z" entry inside tf.download(...).
coordinates=()
while IFS= read -r coordinate; do
  coordinates+=("${coordinate}")
done < <(
  awk '/^tf\.download\(/,/^\)/' "${root}/MODULE.bazel" \
    | grep -oE '"[^"]+/[^"]+:[0-9]+\.[0-9]+\.[0-9]+"' \
    | tr -d '"' | sort -u
)
if [[ ${#coordinates[@]} -eq 0 ]]; then
  printf 'no provider coordinates found in tf.download of %s\n' "${root}/MODULE.bazel" >&2
  exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT
# Ignore local CLI configuration so a mirror or plugin cache can never stand
# in for the registry while hashes are recorded.
: >"${work}/empty.tfrc"
export TF_CLI_CONFIG_FILE="${work}/empty.tfrc"
unset TF_PLUGIN_CACHE_DIR
platform_flags=()
for platform in "${platforms[@]}"; do
  platform_flags+=("-platform=${platform}")
done

{
  printf '# Generated by src/bazel/module_deps/update_tofu_providers_lock.sh; do not edit.\n'
  printf '# Regenerate with: mise exec -- src/bazel/module_deps/update_tofu_providers_lock.sh\n'
  printf '# One `tofu providers lock` block per tf.download mirror coordinate in MODULE.bazel.\n'
  printf '# The tf extension fails when a registry sha256 is not among its zh: hashes.\n'
} >"${work}/lock.hcl"

for coordinate in "${coordinates[@]}"; do
  source="${coordinate%%:*}"
  version="${coordinate##*:}"
  dir="${work}/${source//\//_}_${version}"
  mkdir -p "${dir}"
  printf '{"terraform":[{"required_providers":[{"p":{"source":"%s","version":"%s"}}]}]}\n' \
    "${source}" "${version}" >"${dir}/versions.tf.json"
  printf 'locking %s\n' "${coordinate}" >&2
  (cd "${dir}" && tofu providers lock "${platform_flags[@]}" >/dev/null)
  printf '\n' >>"${work}/lock.hcl"
  grep -v '^#' "${dir}/.terraform.lock.hcl" | sed '/./,$!d' >>"${work}/lock.hcl"
done

mv "${work}/lock.hcl" "${lock}"
printf 'wrote %s\n' "${lock}" >&2

cd "${root}"
bazel mod deps --lockfile_mode=update >/dev/null
printf 'updated MODULE.bazel.lock for this host; the other os/arch entries need the same command on those hosts\n' >&2
