"""Protects retained fleet identities and data across runtime lifecycle commands."""

# ruff: file-ignore[import-private-name]

from __future__ import annotations

import os
import shutil
import subprocess
import time

from infra.tools.cloud_emulator.engine.compose import (
    GIT_DAEMON_COMMAND,
    GIT_DAEMON_DOCKERFILE,
    GIT_DAEMON_LEGACY_IMAGES,
    GIT_DAEMON_USER,
    Fleet,
    _collect_node_create_args,
    _collect_node_host_args,
    _collect_node_mount_args,
    _collect_node_network_args,
    _ensure_k3s_runtime_image,
    _pinned_k3s_runtime_tag,
    _prepare_runtime_images,
    _recreate_node_container,
    _resolve_image_tag_and_id,
    _resume_retained_children,
    _start_services,
    _validate_retained_node_images,
    compose,
    configuration,
    connect_registry,
    endpoint_address,
    find_git_daemon,
    find_headscale_daemon,
    find_repo_root,
    inspect_containers,
    load_local_deployment,
    owned_containers,
    reconcile_registry,
    reconcile_restart_policy,
    registry_endpoint_matches,
    restore_registry_endpoint,
    retire_legacy_git_daemon,
    run,
    start,
    stop,
    stop_containers,
    validate_git_address,
    validate_git_daemon,
    validate_git_port,
    validate_managed_git_daemon,
    validate_parent,
)
from infra.tools.cloud_emulator.engine.docker import (
    COLIMA_CPUS,
    COLIMA_DISK_GIB,
    COLIMA_MEMORY_GIB,
    GIB,
    LOCAL_DOCKER_MINIMUM_FREE_PERCENT,
    LOCAL_NODEFS_EVICTION_PERCENT,
    check_docker_running,
    ensure_docker_local,
    trim_colima_sparse_disk,
    validate_local_docker_storage_headroom,
    validate_local_workspace_storage_headroom,
)
from infra.tools.cloud_emulator.engine.readiness import (
    _build_floci_openssl_cnf,
    _pod_identity_client,
    _publish_public_ca,
    _reconcile_pod_identity_ca,
    _reconcile_public_ca,
    _reconcile_single_eks_container,
    _reconcile_single_webhook,
    _reconcile_token_webhook,
    _stage_and_reload_tls,
    _validate_runtime_tls,
    cluster_contexts,
    control_cluster_record,
    ensure_floci_tls,
    ensure_headscale_tls,
    ensure_headscale_user,
    reconcile_eks_containers,
    reconcile_floci_bridge,
    reconcile_tls,
    wait_for_cluster,
    wait_for_floci_clusters,
)
from infra.tools.cloud_emulator.engine.storage import (
    cluster_volumes,
    ensure_storage,
    remove_volumes,
)

__all__ = [
    "COLIMA_CPUS",
    "COLIMA_DISK_GIB",
    "COLIMA_MEMORY_GIB",
    "GIB",
    "GIT_DAEMON_COMMAND",
    "GIT_DAEMON_DOCKERFILE",
    "GIT_DAEMON_LEGACY_IMAGES",
    "GIT_DAEMON_USER",
    "LOCAL_DOCKER_MINIMUM_FREE_PERCENT",
    "LOCAL_NODEFS_EVICTION_PERCENT",
    "Fleet",
    "_build_floci_openssl_cnf",
    "_collect_node_create_args",
    "_collect_node_host_args",
    "_collect_node_mount_args",
    "_collect_node_network_args",
    "_ensure_k3s_runtime_image",
    "_pinned_k3s_runtime_tag",
    "_pod_identity_client",
    "_prepare_runtime_images",
    "_publish_public_ca",
    "_reconcile_pod_identity_ca",
    "_reconcile_public_ca",
    "_reconcile_single_eks_container",
    "_reconcile_single_webhook",
    "_reconcile_token_webhook",
    "_recreate_node_container",
    "_resolve_image_tag_and_id",
    "_resume_retained_children",
    "_stage_and_reload_tls",
    "_start_services",
    "_validate_retained_node_images",
    "_validate_runtime_tls",
    "check_docker_running",
    "cluster_contexts",
    "cluster_volumes",
    "compose",
    "configuration",
    "connect_registry",
    "control_cluster_record",
    "endpoint_address",
    "ensure_docker_local",
    "ensure_floci_tls",
    "ensure_headscale_tls",
    "ensure_headscale_user",
    "ensure_storage",
    "find_git_daemon",
    "find_headscale_daemon",
    "find_repo_root",
    "inspect_containers",
    "load_local_deployment",
    "os",
    "owned_containers",
    "reconcile_eks_containers",
    "reconcile_floci_bridge",
    "reconcile_registry",
    "reconcile_restart_policy",
    "reconcile_tls",
    "registry_endpoint_matches",
    "remove_volumes",
    "restore_registry_endpoint",
    "retire_legacy_git_daemon",
    "run",
    "shutil",
    "start",
    "stop",
    "stop_containers",
    "subprocess",
    "time",
    "trim_colima_sparse_disk",
    "validate_git_address",
    "validate_git_daemon",
    "validate_git_port",
    "validate_local_docker_storage_headroom",
    "validate_local_workspace_storage_headroom",
    "validate_managed_git_daemon",
    "validate_parent",
    "wait_for_cluster",
    "wait_for_floci_clusters",
]
