"""Define git_hook and git_hooks rules to compose and install executable Git hooks across repository stages."""

GitHookInfo = provider(
    doc = "One declared git hook: the stage it runs at and the target it runs.",
    fields = {
        "args": "Fixed arguments passed before the stage's own arguments.",
        "executable": "Executable file of the hook target.",
        "pass_staged_files": "Whether to pass matching staged files as arguments.",
        "pathspecs": "Git pathspecs that trigger this hook; empty means all files.",
        "stage": "Git hook name, such as pre-commit or commit-msg.",
        "summary": "Human description shown while the hook runs.",
        "target": "Label of the target the hook runs, as a workspace-relative string.",
        "tool_executable": "Executable file of the optional tool target, or None.",
    },
)

# Stages this ruleset knows how to write. Each differs in what git passes it:
# commit-msg receives the message file path, pre-push receives refs on stdin,
# and pre-commit receives nothing. The generated dispatcher forwards whatever
# arrives, so a target can read its own stage's contract.
_STAGES = [
    # keep-sorted start
    "commit-msg",
    "post-checkout",
    "post-merge",
    "pre-commit",
    "pre-push",
    "pre-rebase",
    # keep-sorted end
]

_MARKER = "# generated by //src/bazel/rules/git_hooks:defs.bzl"

def _git_hook_impl(ctx):
    tool_exe = ctx.executable.tool if ctx.attr.tool else None
    tool_runfiles = ctx.attr.tool[DefaultInfo].default_runfiles if ctx.attr.tool else None
    hook_runfiles = ctx.attr.src[DefaultInfo].default_runfiles
    if tool_runfiles:
        hook_runfiles = hook_runfiles.merge(tool_runfiles)
    return [
        GitHookInfo(
            stage = ctx.attr.stage,
            target = str(ctx.attr.src.label),
            executable = ctx.executable.src,
            tool_executable = tool_exe,
            summary = ctx.attr.summary or ctx.label.name,
            args = ctx.attr.args,
            pathspecs = ctx.attr.pathspecs,
            pass_staged_files = ctx.attr.pass_staged_files,
        ),
        DefaultInfo(
            files = depset([ctx.executable.src] + ([tool_exe] if tool_exe else [])),
            runfiles = hook_runfiles,
        ),
    ]

git_hook = rule(
    implementation = _git_hook_impl,
    doc = "Declare that one target runs at one git hook stage.",
    attrs = {
        "args": attr.string_list(
            doc = "Fixed arguments placed before the arguments git supplies.",
        ),
        "pass_staged_files": attr.bool(
            default = False,
            doc = "Whether to pass matching staged files as arguments to the target.",
        ),
        "pathspecs": attr.string_list(
            doc = "Git pathspecs that trigger this hook; empty means all files.",
        ),
        "src": attr.label(
            mandatory = True,
            cfg = "exec",
            executable = True,
            doc = "Target the hook runs. Receives the stage's arguments.",
        ),
        "stage": attr.string(
            mandatory = True,
            values = _STAGES,
            doc = "Git hook name this target runs at.",
        ),
        "summary": attr.string(
            doc = "Description printed while the hook runs; defaults to the target name.",
        ),
        "tool": attr.label(
            cfg = "exec",
            executable = True,
            doc = "Optional tool binary passed as the first argument to src.",
        ),
    },
)

def _sh_quote(s):
    """Safely quote a string for use in POSIX/Bash shell scripts."""
    return "'" + s.replace("'", "'\\''") + "'"

def _render_hook_step(hook, stage):
    lines = ["# Gate: %s" % hook.summary]
    has_args = bool(hook.args) or bool(hook.tool_executable)
    if has_args:
        lines.append("cmd_args=()")
        if hook.tool_executable:
            lines.append('cmd_args+=("$runfiles/%s")' % hook.tool_executable.short_path)
        for arg in hook.args:
            lines.append("cmd_args+=(%s)" % _sh_quote(arg))
        args_token = '"${cmd_args[@]}" '
    else:
        args_token = ""

    if hook.pathspecs:
        lines.append("pathspecs=(")
        for spec in hook.pathspecs:
            lines.append("  %s" % _sh_quote(spec))
        lines.append(")")
        lines.append('if ! has_staged_changes "${pathspecs[@]}"; then')
        lines.append('  printf "%%s: %%s (skipped)\\n" "%s" %s >&2' % (stage, _sh_quote(hook.summary)))
        lines.append("else")
        lines.append('  printf "%%s: %%s\\n" "%s" %s >&2' % (stage, _sh_quote(hook.summary)))
        if hook.pass_staged_files:
            lines.append("  staged_files=()")
            lines.append("  while IFS= read -r f; do")
            lines.append('    [ -n "$f" ] && staged_files+=("$f")')
            lines.append('  done < <(git diff --cached --name-only --diff-filter=ACMR -- "${pathspecs[@]}")')
            lines.append("  if ((${#staged_files[@]} == 0)); then")
            lines.append('    printf "%%s: %%s (skipped: no modified files)\\n" "%s" %s >&2' % (stage, _sh_quote(hook.summary)))
            lines.append("  else")
            lines.append('    "$runfiles/%s" %s"${staged_files[@]}"' % (hook.executable.short_path, args_token))
            lines.append("  fi")
        else:
            lines.append('  "$runfiles/%s" %s"$@"' % (hook.executable.short_path, args_token))
        lines.append("fi")
    else:
        lines.append('printf "%%s: %%s\\n" "%s" %s >&2' % (stage, _sh_quote(hook.summary)))
        if hook.pass_staged_files:
            lines.append("staged_files=()")
            lines.append("while IFS= read -r f; do")
            lines.append('  [ -n "$f" ] && staged_files+=("$f")')
            lines.append("done < <(git diff --cached --name-only --diff-filter=ACMR)")
            lines.append("if ((${#staged_files[@]} == 0)); then")
            lines.append('  printf "%%s: %%s (skipped: no modified files)\\n" "%s" %s >&2' % (stage, _sh_quote(hook.summary)))
            lines.append("else")
            lines.append('    "$runfiles/%s" %s"${staged_files[@]}"' % (hook.executable.short_path, args_token))
            lines.append("fi")
        else:
            lines.append('"$runfiles/%s" %s"$@"' % (hook.executable.short_path, args_token))
    lines.append("")
    return lines

def _git_hooks_stage_runner_impl(ctx):
    stage = ctx.attr.stage
    stage_hooks = [
        dep[GitHookInfo]
        for dep in ctx.attr.srcs
        if dep[GitHookInfo].stage == stage
    ]
    deps_for_stage = [
        dep
        for dep in ctx.attr.srcs
        if dep[GitHookInfo].stage == stage
    ]

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    lines = [
        "#!/usr/bin/env bash",
        _MARKER,
        "set -euo pipefail",
        "",
        'runfiles="$PWD"',
        'export RUNFILES_DIR="$(dirname "$runfiles")"',
        'cd "${BUILD_WORKSPACE_DIRECTORY:?stage runner must be run with bazel run}"',
        'export BUILD_WORKSPACE_DIRECTORY="$PWD"',
        'export REPO_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/repo"',
        # Nested Bazel commands reuse the server running this script; see
        # _render_nested_bazel_env in //src/bazel/rules/lint_aspect:format.bzl.
        # LINT.IfChange(nested_output_root)
        'output_base="${runfiles%%/execroot/*}"',
        'export BAZEL_OUTPUT_ROOT="$(dirname "$(dirname "$(readlink "$output_base/install")")")"',
        'bazel_shim_dir="$(mktemp -d "${TMPDIR:-/tmp}/bazel-nested.XXXXXX")"',
        'printf "#!/bin/sh\\nexec \'%s\' --output_base=\'%s\' \\"\\$@\\"\\n" "$(command -v bazel)" "$output_base" >"$bazel_shim_dir/bazel"',
        'chmod +x "$bazel_shim_dir/bazel"',
        'export PATH="$bazel_shim_dir:$PATH"',
        # LINT.ThenChange(//src/bazel/rules/lint_aspect/format.bzl:nested_output_root)
        'export TFLINT_PLUGIN_DIR="${TFLINT_PLUGIN_DIR:-$REPO_CACHE_DIR/tflint/plugins}"',
        'export TF_PLUGIN_CACHE_DIR="${TF_PLUGIN_CACHE_DIR:-$REPO_CACHE_DIR/opentofu/plugins}"',
        'export RUMDL_CACHE_DIR="${RUMDL_CACHE_DIR:-$REPO_CACHE_DIR/rumdl}"',
        'export PYTHONPYCACHEPREFIX="${PYTHONPYCACHEPREFIX:-$REPO_CACHE_DIR/python}"',
        'export RUFF_CACHE_DIR="${RUFF_CACHE_DIR:-$REPO_CACHE_DIR/ruff}"',
        "",
    ]

    if stage == "commit-msg":
        lines += [
            'if [ "$#" -gt 0 ]; then',
            '  message_file="$1"',
            '  case "$message_file" in',
            "    /*) ;;",
            '    *) message_file="$PWD/$message_file" ;;',
            "  esac",
            "  shift",
            '  set -- "$message_file" "$@"',
            "fi",
            "",
        ]

    lines += [
        "has_staged_changes() {",
        "  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then",
        "    return 0",
        "  fi",
        '  if git diff --cached --quiet -- "$@"; then',
        "    return 1",
        "  else",
        "    return 0",
        "  fi",
        "}",
        "",
    ]

    for hook in stage_hooks:
        lines.extend(_render_hook_step(hook, stage))

    ctx.actions.write(output = launcher, content = "\n".join(lines) + "\n", is_executable = True)

    runfiles = ctx.runfiles()
    runfiles = runfiles.merge_all([dep[DefaultInfo].default_runfiles for dep in deps_for_stage])
    runfiles = runfiles.merge(ctx.attr._runfiles_lib[DefaultInfo].default_runfiles)
    all_exes = []
    for h in stage_hooks:
        if h.executable:
            all_exes.append(h.executable)
        if h.tool_executable:
            all_exes.append(h.tool_executable)
    runfiles = runfiles.merge(ctx.runfiles(files = all_exes))
    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

_git_hooks_stage_runner = rule(
    implementation = _git_hooks_stage_runner_impl,
    doc = "Composite executable runner for one git hook stage.",
    attrs = {
        "_runfiles_lib": attr.label(
            default = "@rules_shell//shell/runfiles:runfiles",
        ),
        "srcs": attr.label_list(
            mandatory = True,
            providers = [GitHookInfo],
            doc = "git_hook targets.",
        ),
        "stage": attr.string(
            mandatory = True,
            values = _STAGES,
            doc = "Git hook name this runner executes.",
        ),
    },
    executable = True,
)

def _git_hooks_installer_impl(ctx):
    by_stage = {}
    for dep in ctx.attr.srcs:
        hook = dep[GitHookInfo]
        by_stage.setdefault(hook.stage, []).append(hook)
    if not by_stage:
        fail("{}: srcs is empty; an installer with no hooks installs nothing".format(ctx.label))

    installer = ctx.actions.declare_file(ctx.label.name + ".sh")
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        'cd "${BUILD_WORKSPACE_DIRECTORY:?%s must be run with bazel run}"' % ctx.label.name,
        'hooks_dir="$(git rev-parse --git-path hooks)"',
        'mkdir -p "$hooks_dir"',
        "",
    ]
    for stage in sorted(by_stage):
        pkg = ctx.label.package
        runner_label = "//%s:%s.%s" % (pkg, ctx.attr.runner_prefix, stage) if pkg else "//:%s.%s" % (ctx.attr.runner_prefix, stage)
        hook_script = "\n".join([
            "#!/usr/bin/env bash",
            _MARKER,
            "set -euo pipefail",
            "",
            "if ! command -v bazel >/dev/null; then",
            '  echo "bazel is not on PATH; cannot run the %s hook" >&2' % stage,
            "  exit 127",
            "fi",
            'output_root="${BAZEL_OUTPUT_ROOT:-$PWD/.tmp/state/bazel}"',
            "",
            'chained="$0.chained"',
            'if [ -x "$chained" ]; then',
            '  "$chained" "$@"',
            "fi",
            "",
            'exec env -u GIT_DIR -u GIT_WORK_TREE bazel --output_user_root="$output_root" run --ui_event_filters=-info,-stdout --noshow_progress %s -- "$@"' % runner_label,
            "",
        ])

        lines += [
            'target="$hooks_dir/%s"' % stage,
            'if [ -e "$target" ] && ! grep -qF "%s" "$target"; then' % _MARKER,
            '  if [ -e "$target.chained" ]; then',
            '    echo "refusing to overwrite an existing %s hook: $target ($target.chained already exists)" >&2' % stage,
            "    exit 1",
            "  fi",
            '  mv "$target" "$target.chained"',
            '  printf "chained existing %s hook to %%s\\n" "$target.chained"' % stage,
            "fi",
            "cat >\"$target\" <<'GENERATED_GIT_HOOK'",
            hook_script.rstrip("\n"),
            "GENERATED_GIT_HOOK",
            'chmod +x "$target"',
            'printf "installed %s\\n" "$target"',
            "",
        ]

    ctx.actions.write(output = installer, content = "\n".join(lines) + "\n", is_executable = True)
    return [DefaultInfo(executable = installer)]

_git_hooks_installer = rule(
    implementation = _git_hooks_installer_impl,
    doc = "Writes every declared hook into the repository's git hooks directory.",
    attrs = {
        "runner_prefix": attr.string(
            mandatory = True,
            doc = "Prefix for the stage runner targets.",
        ),
        "srcs": attr.label_list(
            mandatory = True,
            providers = [GitHookInfo],
            doc = "git_hook targets to install.",
        ),
    },
    executable = True,
)

def git_hooks(name, srcs, **kwargs):
    """Group declared hooks and generate stage runners and installer.

    Args:
        name: prefix; runners are `<name>.<stage>` and installer is `<name>.install`.
        srcs: git_hook targets.
        **kwargs: forwarded to runner and installer targets.
    """
    for stage in _STAGES:
        _git_hooks_stage_runner(
            name = "%s.%s" % (name, stage),
            stage = stage,
            srcs = srcs,
            **kwargs
        )
    _git_hooks_installer(
        name = name + ".install",
        runner_prefix = name,
        srcs = srcs,
        **kwargs
    )
