# Configures default values for the s3-gateway-team Helm chart.

team: ""
provider: ""
authAdapter: ""
targetCell: ""
topology: {}
identity: {}
globalStorage:
  bucketPrefix: ""
  bucketSuffix: ""
  endpoint: ""
  provider: ""
readers: all
workspaceGrant:
  members: []
  recordName: ""
  readerRecordName: ""
