# Kustomize entrypoint for gpu-operator network policy and resource quota resources.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # keep-sorted start
  - namespace.yaml
  - network-policy.yaml
  - nfd-cleanup.yaml
  - resource-quota.yaml
  # keep-sorted end
