# ConfigMap configuring cloud object storage destination and credentials for ClickHouse backups.

apiVersion: v1
kind: ConfigMap
metadata:
  name: signoz-clickhouse-backup-provider
  namespace: signoz
  labels:
    app.kubernetes.io/name: clickhouse-backup
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: database-backup
    app.kubernetes.io/part-of: signoz
data:
  # keep-sorted start
  AWS_DEFAULT_REGION: us-east-1
  AWS_ENDPOINT_URL_S3: configured-by-applicationset
  AWS_REGION: us-east-1
  BACKUP_BUCKET: examples-clickhouse-backups
  BACKUP_CELL: ""
  BACKUP_ENGINE: S3
  CLICKHOUSE_BACKUP_URL: configured-by-applicationset
  CLICKHOUSE_COLD_STORAGE_TYPE: local
  CLICKHOUSE_COLD_STORAGE_URL: http://127.0.0.1:9000/telemetry/clickhouse/
  RETENTION_PROVIDER: aws
  # keep-sorted end
