# Defines the PersistentVolumeClaim for cloud-telemetry queue storage buffering.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-telemetry-storage
  namespace: otel-system
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: cloud-telemetry
    app.kubernetes.io/part-of: opentelemetry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
