#!/usr/bin/env python3
"""Tests HTML template rendering and client connection snippets generated by the Paseo SSH instruction server."""

from __future__ import annotations

import importlib.util
import pathlib
import tempfile
import threading
import unittest
from http import HTTPStatus
from http.client import HTTPConnection
from typing import TYPE_CHECKING
from unittest import mock

if TYPE_CHECKING:
    import types


def load_subject() -> types.ModuleType:
    path = pathlib.Path(__file__).with_name("paseo_instructions.py")
    spec = importlib.util.spec_from_file_location("paseo_instructions", path)
    assert spec
    assert spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class SshInstructionPageTest(unittest.TestCase):
    @staticmethod
    def test_serves_coder_proxy_base_path_with_trailing_slash() -> None:
        subject = load_subject()
        subject.InstructionHandler.page = b"ssh instructions"
        with subject.ThreadingHTTPServer((subject.HOST, 0), subject.InstructionHandler) as server:
            thread = threading.Thread(target=server.serve_forever)
            thread.start()
            try:
                connection = HTTPConnection(*server.server_address, timeout=2)
                connection.request("GET", "/ssh/")
                response = connection.getresponse()

                assert response.status == HTTPStatus.OK
                assert response.read() == b"ssh instructions"
            finally:
                connection.close()
                server.shutdown()
                thread.join()

    @staticmethod
    def test_escapes_addresses_and_includes_tabs() -> None:
        subject = load_subject()
        page = subject.ssh_instruction_page(
            'ssh://ldap@example.invalid" autofocus="',
            'vscode://example.invalid/" onclick="',
            'test-ws" <script>',
        )

        assert b'example.invalid" autofocus="' not in page
        assert b"example.invalid&quot; autofocus=&quot;" in page
        assert b'test-ws" <script>' not in page
        assert b"test-ws&quot; &lt;script&gt;" in page
        assert b'role="tablist"' in page
        assert b">SSH (Terminal)</button>" in page
        assert b">Herdr</button>" in page
        assert b">VS Code</button>" in page
        assert b">Paseo</button>" in page
        assert b">Claude</button>" in page
        assert b">Codex</button>" in page
        assert b">~/.ssh/config</button>" in page
        assert b">Open in Terminal</a>" in page
        assert b">Open in VS Code</a>" in page
        assert b"herdr --remote" in page
        assert b"herdr machine add" in page
        assert b"Settings &gt; Add host &gt; Remote SSH" in page
        assert b"Claude Code Desktop SSH Environment" in page
        assert b"Codex Desktop Remote Environment" in page
        assert b"Remote Project Path" in page
        assert b"Host " in page

    @staticmethod
    def test_health_requires_marker_and_listening_ssh() -> None:
        subject = load_subject()
        with tempfile.TemporaryDirectory() as directory:
            marker = pathlib.Path(directory, "ssh-ready")
            assert not subject.ssh_is_ready(marker)
            marker.touch()
            with mock.patch.object(subject.socket, "create_connection", side_effect=OSError):
                assert not subject.ssh_is_ready(marker)
            connection = mock.MagicMock()
            connection.__enter__.return_value = connection
            with mock.patch.object(subject.socket, "create_connection", return_value=connection):
                assert subject.ssh_is_ready(marker)


if __name__ == "__main__":
    unittest.main()
