"""Check targets for the dragonfly_peer Argo CD component."""

load("@rules_helm//helm:defs.bzl", "helm_template")
load("@rules_kustomize//kustomize:kustomize.bzl", "kustomization", "kustomized_resources")
load("//src/bazel/rules/build_graph_coverage:defs.bzl", "package_sources")
load("//src/bazel/rules/kubernetes_manifests:defs.bzl", "manifest_checks")

exports_files(
    [
        "helm/client-image.yaml",
        "helm/values.yaml",
    ],
    visibility = ["//src/infra/argocd/apps:__pkg__"],
)

kustomization(
    name = "base",
    srcs = glob(["kustomize/**"]),
    file = "kustomize/kustomization.yaml",
)

kustomized_resources(
    name = "base_render",
    kustomization = ":base",
    visibility = ["//visibility:public"],
)

manifest_checks(
    name = "base_manifest",
    rendered = ":base_render",
)

helm_template(
    name = "vendor-helm-render",
    chart = "@vendor_helm_dragonfly_peer//:dragonfly",
    opts = [
        "--include-crds",
        "--namespace",
        "manifest-checks",
    ],
    values = [
        "helm/values.yaml",
        "helm/client-image.yaml",
    ],
    visibility = ["//src/infra/argocd/apps:__pkg__"],
)

package_sources()

manifest_checks(
    name = "vendor-helm",
    kube_lint_config = "//src/bazel/rules/kubernetes_manifests:kube-linter-vendor.yaml",
    rendered = ":vendor-helm-render",
)
