"""Defines OpenTofu module check targets for GCP Artifact Registry container repositories."""

load("@rules_tf//tf:def.bzl", "tf_module")
load("//src/bazel/rules/build_graph_coverage:defs.bzl", "package_sources")

tf_module(
    name = "gcp",
    providers = [
        "google",
    ],
    skip_validation = True,
    deps = [
        "//src/infra/terraform/components/registry/_interface",
    ],
)

package_sources()
