# Helm values for Rclone CSI node plugin providing secure inline volume mounts to workspaces.

fullnameOverride: rclone-csi

feature:
  enableFSGroupPolicy: true
  enableInlineVolume: true
  propagateHostMountOptions: false

rbac: {create: false}

image:
  csiProvisioner:
    repository: registry.k8s.io/sig-storage/csi-provisioner
    tag: v6.2.0@sha256:6be9f63ca4caa6c46aae55aa372500949d8a21473d72f819da1f746076b32d4e
  livenessProbe:
    repository: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.18.0@sha256:c4cc074199c045dd73ab85f28897e2a32f4d6f38ffdba4f3b13b8007ccbd3570
  nodeDriverRegistrar:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.16.0@sha256:ab482308a4921e28a6df09a16ab99a457e9af9641ff44fb1be1a690d07ce8b70
  rclone:
    repository: ghcr.io/veloxpack/csi-driver-rclone
    tag: v0.5.0@sha256:38d087c4db803b9d9478b4c8f4d4b7fa1483120107fe796a00ca3f34f9fa5f25

node:
  cache: {enabled: false}
  logLevel: 2
  name: rclone-csi-node
  priorityClassName: node-agents
  resources:
    livenessProbe:
      limits: {cpu: 250m, ephemeral-storage: 128Mi, memory: 128Mi}
      requests: {cpu: 30m, ephemeral-storage: 32Mi, memory: 32Mi}
    nodeDriverRegistrar:
      limits: {cpu: 250m, ephemeral-storage: 128Mi, memory: 128Mi}
      requests: {cpu: 30m, ephemeral-storage: 32Mi, memory: 32Mi}
    rclone:
      limits: {cpu: 500m, ephemeral-storage: 1Gi, memory: 1Gi}
      requests: {cpu: 30m, ephemeral-storage: 128Mi, memory: 128Mi}
  tolerations:
    - {effect: NoSchedule, key: google.com/tpu, operator: Equal, value: present}
    - {effect: NoSchedule, key: nvidia.com/gpu, operator: Equal, value: present,}

controller:
  name: rclone-csi-controller
  replicas: 0
  priorityClassName: node-agents
  resources:
    csiProvisioner:
      limits: {cpu: 250m, ephemeral-storage: 128Mi, memory: 128Mi}
      requests: {cpu: 30m, ephemeral-storage: 32Mi, memory: 32Mi}
    livenessProbe:
      limits: {cpu: 250m, ephemeral-storage: 128Mi, memory: 128Mi}
      requests: {cpu: 30m, ephemeral-storage: 32Mi, memory: 32Mi}
    rclone:
      limits: {cpu: 500m, ephemeral-storage: 1Gi, memory: 256Mi}
      requests: {cpu: 30m, ephemeral-storage: 128Mi, memory: 128Mi}
serviceAccount:
  controller: rclone-csi-controller-sa
  node: rclone-csi-node-sa

storageClass: {create: false}
