"""Defines OpenTofu module check targets for AWS EKS control plane and node group provisioning."""

load("@rules_tf//tf:def.bzl", "tf_module")
load("//src/bazel/rules/build_graph_coverage:defs.bzl", "package_sources")

tf_module(
    name = "aws",
    providers = [
        "aws",
    ],
    skip_validation = True,
    deps = [
        "//src/infra/terraform/components/cluster/_interface",
    ],
)

package_sources()
