"""Check targets for the cluster_access Argo CD component."""

# gazelle:resolve py yaml @dev_python_deps//pyyaml

load("@rules_kustomize//kustomize:kustomize.bzl", "kustomization", "kustomized_resources")
load("@rules_python//python:defs.bzl", "py_test")
load("//src/bazel/rules/build_graph_coverage:defs.bzl", "package_sources")
load("//src/bazel/rules/kubernetes_manifests:defs.bzl", "manifest_checks")

kustomization(
    name = "base",
    srcs = glob(["kustomize/**"]),
    file = "kustomize/kustomization.yaml",
)

kustomized_resources(
    name = "base_render",
    kustomization = ":base",
    visibility = ["//visibility:public"],
)

manifest_checks(
    name = "base_manifest",
    rendered = ":base_render",
)

py_test(
    name = "team_open_submitter_test",
    size = "small",
    srcs = ["team_open_submitter_test.py"],
    args = ["$(location :base_render)"],
    data = [":base_render"],
    deps = ["@dev_python_deps//pyyaml"],  # keep
)

package_sources(exclude = [
    "**/*.py",
])
