# Defines workload identity ServiceAccount for scheduled in-cluster Prowler CSPM scans.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prowler
  namespace: prowler
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: prowler
  annotations:
    automount-service-account-token: "true"
automountServiceAccountToken: true
