# ClusterIssuer providing local CA certificate signing for internal cluster services.

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-local-ca-bootstrap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-local-ca
  namespace: cert-manager-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  isCA: true
  commonName: cluster-local-ca
  secretName: cluster-local-ca
  duration: 26280h
  renewBefore: 2160h
  privateKey:
    rotationPolicy: Never
  issuerRef:
    name: cluster-local-ca-bootstrap
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-local-ca
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ca:
    secretName: cluster-local-ca

