"""Check targets for the buildbuddy_executor Argo CD component."""

load("@rules_helm//helm:defs.bzl", "helm_template")
load("//src/bazel/rules/build_graph_coverage:defs.bzl", "package_sources")
load("//src/bazel/rules/kubernetes_manifests:defs.bzl", "manifest_checks")

helm_template(
    name = "vendor-helm-render",
    chart = "@vendor_helm_buildbuddy_executor//:buildbuddy-executor",
    opts = [
        "--include-crds",
        "--namespace",
        "manifest-checks",
    ],
    values = ["helm/values.yaml"],
)

package_sources()

manifest_checks(
    name = "vendor-helm",
    kube_lint_config = "//src/bazel/rules/kubernetes_manifests:kube-linter-vendor.yaml",
    rendered = ":vendor-helm-render",
)

helm_template(
    name = "vendor-helm-render-gpu",
    chart = "@vendor_helm_buildbuddy_executor//:buildbuddy-executor",
    opts = [
        "--include-crds",
        "--namespace",
        "manifest-checks",
    ],
    values = [
        "helm/values.yaml",
        "helm/pool-gpu.yaml",
    ],
)

manifest_checks(
    name = "vendor-helm-gpu",
    kube_lint_config = "//src/bazel/rules/kubernetes_manifests:kube-linter-vendor.yaml",
    rendered = ":vendor-helm-render-gpu",
)
