# Namespace hosting BuildBuddy cache, enterprise cache proxy, and remote build executors.

apiVersion: v1
kind: Namespace
metadata:
  name: buildbuddy
  labels:
    # keep-sorted start
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: buildbuddy
    app.kubernetes.io/part-of: cluster-runtime
    cost-center: shared-infrastructure
    environment: production
    kueue.x-k8s.io/managed: "true"
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn-version: latest
    pod-security.kubernetes.io/warn: privileged
    # keep-sorted end
