# Configures base Helm values for Envoy Gateway control plane installed once per control cluster.

crds:
  enabled: true
commonLabels: {}
config:
  envoyGateway:
    extensionApis:
      enableBackend: true
global:
  images:
    envoyGateway:
      image: >-
        docker.io/envoyproxy/gateway:v1.9.2@sha256:9d67017c442a70e6ae9f1a358e6c80eb653c67c2e40823d9a991e0daf37ba926
    envoyProxy:
      # LINT.IfChange(envoy-proxy-runtime-image)
      image: >-
        docker.io/envoyproxy/envoy:distroless-v1.39.0@sha256:7877ad87afd7459e1bd2a077ff601fec7c93aeecd62e71664560d96328c62cf4
      # LINT.ThenChange(//src/infra/argocd/components/envoy_gateway_instance/helm/values.yaml:envoy-proxy-runtime-image)
      pullPolicy: IfNotPresent
    ratelimit:
      image: >-
        docker.io/envoyproxy/ratelimit:17b1956c@sha256:871098f54d99ad612abdd455e39632be6d990937be2e46eecf4e39f65d948a94
deployment:
  replicas: 2
  priorityClassName: cluster-operators
  envoyGateway:
    resources:
      requests: {cpu: 100m, memory: 256Mi}
      limits: {cpu: 500m, memory: 1Gi}
  pod:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: envoy-gateway
                  app.kubernetes.io/name: gateway-helm
                  control-plane: envoy-gateway
              topologyKey: kubernetes.io/hostname
            weight: 100
    topologySpreadConstraints: []
    annotations:
      signoz.io/path: /metrics
      signoz.io/port: "19001"
      signoz.io/scrape: "true"
podDisruptionBudget: {minAvailable: 1}
service:
  type: ClusterIP
