# Kustomize base for BuildBuddy Enterprise Cache Proxy companion resources.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # keep-sorted start
  - external-secrets.yaml
  - namespace.yaml
  - network-policy.yaml
  # keep-sorted end
