# Declares Kubernetes resources and policies for the k8s-cleaner component.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # keep-sorted start
  - cleaner-corrupt-image.yaml
  - cleaner-pv.yaml
  # keep-sorted end
