# AWS Secrets Manager ClusterSecretStore for external-secrets operator in AWS clusters.

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  conditions:
    - namespaces:
        # keep-sorted start
        - application-identity
        - argocd
        - atlantis
        - cert-manager-system
        - coder
        - dex
        - envoy-gateway-system
        - s3-system
        - signoz
        - tailscale-system
        # keep-sorted end
  provider:
    aws:
      service: SecretsManager
      region: configured-by-applicationset.invalid
